### ISSUE TITLE
Getting a working web-worker in Safari under SvelteKit

### ISSUE THREAD

**Issue by FunMiles** [sveltejs/kit#1780]
I have been trying to get a web worker running with SvelteKit. I got it working for Chrome browser but not for Safari.
I import and start the web-worker using:
```js
import SyncWorker from '$lib/workers/SyncWorker?worker'
let theWorker = await new SyncWorker();
```

This will start a web-worker on all browser correctly if there are no imports. I understand from Vite that it will not work on some worker in dev mode. But it is supposed to work correctly in production mode. However when I build the code and then run the preview and the worker's code has:
```js
import Parse from 'parse/dist/parse.min.js';
```
Then I get an error in the console on Safari (Chrome works):
```
SyntaxError: Unexpected token '{'. import call expects exactly one argument.
```

If anyone has gotten a web-worker running, I'd love to have a sample or work around this issue.

**Comment by ebeloded** [comment]
The issue is that Vite doesn't support classic workers. Bump up the issue here: https://github.com/vitejs/vite/issues/2550.

The workaround right now is to have a separate esbuild process for bundling your worker and saving it alongside your static assets.

**Comment by ebeloded** [comment]
Quick update: it turns out that your code should work even without classic workers support in `vite@2.4.0-beta.2`, as the issue you describe is resolved in a recent PR (https://github.com/vitejs/vite/pull/2494)

**Comment by FunMiles** [comment]
Thanks @ebeloded. I had seen your post of that issue, I had followed up to the apparent PR that I found abandoned and put a plus on your workaround. I am glad there's now a working solution. I will give it a try.

**Comment by FunMiles** [comment]
@ebeloded I need a bit of help here. How do I use that version of `vite` in svelte kit? I try adding the dependency to package.json, but then it complains that 
```
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.2.3" from @sveltejs/vite-plugin-svelte@1.0.0-next.10
```

**Comment by FunMiles** [comment]
I've made progress with the `vite@2.4.0-beta.2`. But it still doesn't work. I am getting different error messages:
```
[vite:worker] UMD and IIFE output formats are not supported for code-splitting builds.
file: /Users/michel/Development/Androdev/Svelte/Kit/KitFlightLog/kitflightlog/src/lib/workers/SyncWorker.ts?worker&inline
> UMD and IIFE output formats are not supported for code-splitting builds.
Error: UMD and IIFE output formats are not supported for code-splitting builds.
```

**Comment by FunMiles** [comment]
Further notes:
I got it working using the above PR. It's a bit tricky as I had to download the svelte-kit distribution, modify `packages/kit/package.json` to change the version of vite, then run `pnpm i` followed by `pnpm build` then go back to my code and use ` "@sveltejs/kit": "file:../kit/packages/kit",` in my `package.json`. Finally fix `hooks.ts` to replace `render` with `resolve`.
