### ISSUE TITLE
Page scroll position not reset to top on navigation (regression)

### ISSUE THREAD

**Issue by geoffrich** [sveltejs/kit#2733]
### Describe the bug

When navigating to a new page, if you are already scrolled partway down the page, the next page load will keep the current scroll position and not scroll back to the top.

I believe this broke with next-193. When I install next-192, this does not happen -- navigating to a new page always scrolls to the top, just like regular browser navigation.

### Reproduction

Init the SvelteKit demo project. Add the following paragraph in `about.svelte` after the last paragraph.

```html
<p>Go <a href="/">home</a></p>
```

Make the browser window small enough so that the page scrolls and scroll to the bottom of the page. Click the Home link. The Home page loads, but does not scroll to the top (i.e. the nav bar is not visible).

![scroll-bug](https://user-images.githubusercontent.com/4992896/140010888-334fafbd-e66c-4e99-81f0-c3b591855f34.gif).

Tested in Chrome and Firefox on Windows 10.

### System Info

```shell
System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Memory: 7.79 GB / 12.40 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.1.1 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.193 => 1.0.0-next.193
    svelte: ^3.34.0 => 3.44.1
```

### Severity

serious, but I can work around it

**Comment by rmunn** [comment]
Almost certainly caused by something in https://github.com/sveltejs/kit/pull/2668, as that was merged in between the next.192 and next.193 releases and it's a scroll-related feature.

**Comment by raymclee** [comment]
I'm having same problem. What is the workaround please?

**Comment by geoffrich** [comment]
@raymclee for now, downgrade to 1.0.0-next.192. It's only 1 version back so you shouldn't be missing much ([changelog](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next193))

```
npm i @sveltejs/kit@1.0.0-next.192
```

**Comment by rosslh** [comment]
With `1.0.0-next.194` this is resolved on Chrome but it is still broken for me on Firefox

**Comment by bluwy** [comment]
@rosslh I'm not able to reproduce in Firefox with the repro steps given in this issue. Do you have a different repro for the issue?

**Comment by jgrieger** [comment]
@bluwy @rosslh With `v1.0.0-next.199` it is still not working correctly for me on Firefox (94.0 Linux Mint and 94.1.2 Android 12).
I can reproduce it by simply navigating back and forth via links on the footer. Worth noting: I toggle between two non-root pages, links to the "/" route always work.

**Comment by bluwy** [comment]
@jgrieger We haven't changed much in the router since this fix, so I'm guessing the root issue is the same as #2794 (newer). I haven't found a way around it yet.

**Comment by rosslh** [comment]
My issue was resolved at some point, not sure which version.

**Comment by josh-collinsworth** [comment]
Seeing this issue on `1.0.0-next.21` in both Firefox and Chrome on MacBook Pro.

**Comment by josh-collinsworth** [comment]
Fixed for me in `@sveltejs/kit@1.0.0-next.199`.

**Comment by jgrieger** [comment]
Solve for me with `@sveltejs/kit@1.0.0-next.201` :+1:.

**Comment by andreasnuesslein** [comment]
i still have this issue with `@sveltejs/kit@1.0.0-next.202`

**Comment by sbutler-gh** [comment]
I was having this issue recently for me in `@sveltejs/kit@1.0.0-next.198" on MacOS / Chrome.  Rolling back to `npm i @sveltejs/kit@1.0.0-next.192` solved it for me for now (thanks @geoffrich )

**Comment by johnknoop** [comment]
Will this be resolved in an upcoming release? It's not a huge problem for me so I'd rather not downgrade to an earlier version, but it is a bit ugly so it would be great if it was solved a some point.

**Comment by akkie** [comment]
I have the same issue on MacOs with 1.0.0-next.240 on all available browsers. @benmccann please can we reopen this bug. I have seen that there are some related issues which are already closed. I'm not sure it makes sense to create a new bug every time this problem seems to be fixed.

**Comment by Jose-LolG0D** [comment]
Having the same issue on MacOs with SvelteKit v1.0.0-next.232

**Comment by nhe23** [comment]
I cannot reproduce this issue. Scroll position is reset to the top as it should be for me. Im also using MacOS and the current SvelteKit Version (v1.0.0-next.242) and tested with Chrome and Safari using links to different routes (explicitly not "/"). It would be great if someone who has this issue could provide a repository to reproduce and detailed system information.

**Comment by johnknoop** [comment]
I can only reproduce it on my iPhone, not on my laptop (Windows).

If you have an iPhone, try and visit my site https://hublin.se scroll down a bit, then use the hamburger menu to go to the page "Skapa konto" (means "create account" in Swedish). You'll find that the scroll position isn't reset, since you can scroll up a bit.

**Comment by Jose-LolG0D** [comment]
A little bit more info: I just updated to SvelteKit v1.0.0-next.245, and scroll is still not reseting on page change, tried it on firefox, brave, and safari, which are all updated. You can as well visit my website to see it not working [https://painhas.com], just go there, scroll down a bit, and click in "originals" on the header (for example). Also im on macOS Monterey 12.2 beta to be more specific.

**Comment by akkie** [comment]
Here is an example: https://github.com/akkie/svelte-scroll-issue

Steps to reproduce:
- `yarn run dev`
- open http://localhost:3000
- Scroll to bottom
- Click Log in

Sometimes on the first reload the scroll to top works. In this case scroll to bottom and click on another side.

**Comment by nhe23** [comment]
I can reproduce this issue with the given repository. The native `scrollTo` function that is used to scroll to the top does not work if the rootElement in the __layout.svelte has `overflow: auto;` and `max-height: 100vh;`. In the repository @akkie provided it is caused by the 'Drawer' component.
So something like this: 
```js
<div style="max-height: 100vh; overflow-y: auto;">
	<main>
		<slot />
	</main>
	<Footer />
</div>
```
in the _layout.svelte prevents the native scrollTo function to work properly ([https://stackoverflow.com/questions/1174863/javascript-scrollto-method-does-nothing](https://stackoverflow.com/questions/1174863/javascript-scrollto-method-does-nothing))
I'm not quite sure if SvelteKit can do anything about that as this issue is caused by CSS inside the SvelteKit App.

**Comment by jgrieger** [comment]
Maybe sveltekit as a cool tool could emit a warning if someone uses scrollTo() and has the given styles applied in the root component. :-)

**Comment by johnknoop** [comment]
@nhe23 in my case I don't have any such max-height so maybe that isn't the only thing that causes the failure to reset scroll?

**Comment by benmccann** [comment]
@johnknoop can you provide code and instructions for reproducing? as stated earlier, it's hard to debug without the code

**Comment by johnknoop** [comment]
@benmccann sure! Can I message you privately somehow? I don't want to make my repo publicly available.

**Comment by nhe23** [comment]
@johnknoop maybe you can create a minimal repo with just the pages and components that are needed to reproduce the issue. This way you can leave the stuff out you don't want wo be publicly available and everyone can contribute to solve this issue.

**Comment by benmccann** [comment]
I have the same username on Discord. Though other folks like @nhe23, @bluwy, or @geoffrich might have more time to look at this, so if one of them are interested or even better if you can make a minimal repro like @nhe23 suggested that you can make publicly available that might be better. I don't know that I can really commit to being able to look at this at the moment

**Comment by johnknoop** [comment]
Ok, I've created a small repo now that you can use: https://github.com/johnknoop/scrollbug

There are two says two reproduce the issue:

### 1 / Desktop
Browser: Chrome on Win 11
On the start page, scroll all the way down to the bottom and click on the link in the footer called "skapa konto".
Expected result: the scroll position would be reset to the top of the page.
Observed result: the scroll position is stuck at the bottom of the page.

### 2 / Mobile
Browser: iOS Safari
On the start page, scroll down a bit and click the green button that says "Starta nu"..
Expected result: the scroll position would be reset to the top of the page.
Observer result: the scroll position is ~100px or so from the top, just enough for the `<h1>` to be visible in the viewport (not sure if this is by design).

**Comment by johnknoop** [comment]
![issue-1](https://user-images.githubusercontent.com/3394270/151661142-c5d98bd7-a5df-4055-89f1-51a90015524b.gif)

Here's a screen recording of the desktop version of the issue. Not sure if it may be caused by the fact that I have `scroll-behavior: smooth` on my site? That shouldn't be a factor on iOS Safari though, since smooth scrolling isn't supported by that browser.

**Comment by nhe23** [comment]
Thank you @johnknoop for creating a repo. Unfortunately I have some issues with it (using SvelteKit 1.0.0-next.250):
1.  
<img width="886" alt="image" src="https://user-images.githubusercontent.com/19340684/151664876-89c961ec-66b2-4899-8e4f-e25b44b7cbb6.png">

2. `$page.path has been replaced by $page.url.pathname` ... you're probably using an older version of SvelteKit locally as this change was made a few weeks ago.

However I can see the issue on your site [hublin.se](hublin.se) using Chrome on MacOS. If I disable `scroll-behavior: smooth` for html and body in the DevTools it works. 
Your site is probably on SvelteKit 1.0.0-next.201. Have you tried the current version yet?

**Comment by johnknoop** [comment]
@nhe23 I just upgraded to `1.0.0-next.224` and the scroll position issue seems resolved. I needed to fix that `$page.path`->`$page.url.pathname` thing.

However I couldn't upgrade beyond version `1.0.0-next.224`. If I tried `1.0.0-next.225` or higher, I get the same sass error as you. I'm not sure what that is, but I'll debug that separately.

Thanks for you help!

**Comment by akkie** [comment]
> 

Is it possible to override the scroll behavior? So instead scrolling on the windows object, it would be great to scroll on the drawer object. This is also the suggestion for DaisyUI drawer component. https://github.com/saadeghi/daisyui/issues/431#issuecomment-1023514827

From my perspective, it would make sense, if SvelteKit would allow to set which element should be scrolled.

**Comment by akkie** [comment]
OK, git it working with:

```ts
let drawerContent: HTMLDivElement;
onMount(() => {
    const _scroll = drawerContent.scrollTo;
    window.scrollTo = function() {
        _scroll.apply(drawerContent, arguments)
    }
});
```

**Comment by nhe23** [comment]
I think this can be handled by SvelteKit as well. But making something like this configurable would bloat the configuration. However we could improve the page reset logic by checking if there's a root element in the html body that has a `scrollHeight` >  0 and if so setting it to 0. I'll try that solution out and create a PR if it is feasible.

**Comment by nikosgpet** [comment]
In my case, I had to remove the following from my css: 

```
html {
  overflow: hidden;
}
```

As an alternative, this also works:
```
onMount(() => {
  document.body.scrollTop = 0;
});
```

This is a general thing in javascript, as shown in this [stackoverflow issue](https://stackoverflow.com/questions/14622963/javascript-css-window-scrollto0-0-not-working). 

Maybe svelte-kit should take into consideration that `html` overflow might be hidden and in that case `body` should be scrolled instead.

**Comment by nhe23** [comment]
@nikosgpet could you maybe provide a  minimal repo? I already created a PR and I'd like to check if my changes also fix your usecase.

**Comment by nikosgpet** [comment]
I created a reproduction repo that you can access [here](https://github.com/nikosgpet/bug-2733).

I uploaded a demo in Cloudflare Pages. [Here is a demo](https://55fd7f2c.bug-2733.pages.dev/) functioning correctly. When you scroll to the bottom of the page and click on the link, you arrive at the top of the new page.

If I add the following css, the bug appears: 

```
html {
	height: 100%;
	overflow: hidden;
}

body {
	height: 100%;
	overflow: auto;
}
```

You can see a [demo of the bug here](https://9148c1ec.bug-2733.pages.dev/). Now when we scroll to the bottom of the page, when we click the link we no longer arrive at the top of the new page, but somewhere in the middle.

**Comment by am283721** [comment]
Removing `scroll-behavior: smooth;` from `html` was what helped me work around the issue for now using `next.260` with Firefox on MacOS Monterey.

**Comment by urbantrout** [comment]
This fixed it for me:

```js
import { afterNavigate, beforeNavigate } from '$app/navigation';

beforeNavigate(() => {
    document.documentElement.style.scrollBehavior = 'auto';
});
afterNavigate(() => {
    document.documentElement.style.scrollBehavior = '';
});
```

**Comment by SamuelEarl** [comment]
These are great comments! This was my situation and what worked for me:

I have two independently scrolling panels in the `__layout.svelte` file:

```
<div id="layout">
  <div id="sidebar">
    <Sidebar />
  </div>
  <main id="main">
    <slot />
  </main>
</div>

<style>  
  #layout {
    height: 100vh;
    display: flex;

    & #sidebar {
      width: 20%;
      overflow-y: auto;
    }

    & #main {
      flex: 1;
      padding: 0 20px 100px 20px;
      overflow-y: auto;
    }
  }
</style>
```
The `sidebar` element contains the navigation and the `<main>` element contains my content. (The content in the `<main>` element is the part whose scroll position needs to be reset to the top when a user navigates to a new page.) The issue for me was when I would scroll down one page and then click on another page in the navigation, then the scroll position of the content in the `<main>` element would remain scrolled down the page. Borrowing some of the ideas posted above, I was able to fix it by adding the `afterNavigation` hook in my `__layout.svelte` file, like this:

```
<script>
  import { afterNavigate } from "$app/navigation";
  import Sidebar from "./_sidebar.svelte";

  afterNavigate(() => {
    document.getElementById("main").scrollTop = 0;
  });
</script>
```
Since the scroll position of the content in the `<main>` element is what needed to be reset, I referenced the `<main>` element inside the `afterNavigation` hook and reset its scroll position.

I hope that helps someone else.

**Comment by tzwel** [comment]
Removing `100vh` from `<body>` fixed it for me

**Comment by geniuskrul** [comment]
Same here: https://github.com/babakfp/svelte-movies

‍```
"@sveltejs/kit": "1.0.0-next.328",
```

Video:
https://user-images.githubusercontent.com/97315614/168525690-2de734dc-972e-42ec-976c-19b4a42c1855.mp4

**Comment by danilodeveloper** [comment]
I'm still facing this issue in the Svelte 3.48.0 on chrome and firefox. Until the fix comes out I'm using the `onMount` function with `window.scrollTo(x-coord, y-coord)`.

**Comment by jamalvarez** [comment]
We noticed we had this issue as well; after checking we saw we were using `height:100vh;` on a div
we replaced it for `min-height:100vh;` and this stopped happening

**Comment by jKm00** [comment]
I noticed that for me if I scroll down to a link and then click on it right away, it does not scroll to the top of the linked page. But if I wait about half a second from scrolling down to the link and then pressing the link, it works just find and scrolls to the top of the linked page.

**Comment by dongumayagay** [comment]
experiencing this while using height:100% on both html and body. can't really remove those because those are already fixed for 100vh in mobile brower issue.

**Comment by beerinho** [comment]
It's a bit hacky, but I got around it by adding the following to my root `+layout.svelte` file:
```js
let scrollHistory = []

beforeNavigate((navigation) => {
         // I have everything wrapped in a `main` tag so that's the part I need to scroll
	const main = document.querySelector('main');

	scrollHistory.push({
		to: navigation.to,
		from: navigation.from,
		scrollY: main.scrollTop
	});
});

afterNavigate((navigation) => {
	const main = document.querySelector('main');
	const routeHistory = scrollHistory.find((history) => {
		return history.from.url.pathname === navigation.to.url.pathname;
	});

        // I only want to revert the scroll when going back in the history
	if (routeHistory && navigation.type == 'popstate') {
		main.scrollTo(0, routeHistory.scrollY);
		// I reset the scrollHistory here so that the array doesn't store lots of unneeded values, but could also just add and remove the necessary ones if the page structure is more complex
		scrollHistory = [];
	} else {
	        // if it's a page that isn't in the scrollHistory, simply scroll to the top of the page
		main.scrollTo(0, 0);
	}
});
```

**Comment by mefaba** [comment]
I tried to reproduce initial issue, the bug does not seem to exist anymore. page scrolls to the top without as expected. @geoffrich does this bug still exist?

**Comment by jacktho** [comment]
I'm running into this but only in Firefox. Removing height 100vh/100% from html and body does not fix it for me.

**Comment by thobson** [comment]
Yet another workaround ...

```
// src/routes/+layout.svelte
<script lang="ts">
  import { afterNavigate } from "$app/navigation";
  
  let navbar: HTMLElement;

  afterNavigate(() => {
    if (navbar) { 
      navbar.scrollIntoView();
    }
  });
</script>

<!-- this is at the top of the page -->
<nav bind:this={navbar}>
 ...
</nav>
```

**Comment by nhunzaker** [comment]
I'm hitting this issue for my mobile website when switching between the same route with different url parameters.

We have a header and footer and were using `display: flex` to create a scrollable area within a `main` tag, like:


```html
<body>
  <div> <-- svelte-kit root, height: 100%;
    <Header />
    <Main /> <-- this is the scrollable area
    <Footer />
  </div>
</body>
```

As far as I can see, the problem is that scrolling doesn't get reset for the my scrolling `<main>` element that acts as the content body.

I'm fixing this by adding `position: sticky` on my header and footer, which allowed me to make the body element act as the scroll container:

```html
<body>  <-- this is now the scrollable element
  <div> <-- svelte-kit root, min-height: 100%;
    <Header /> <-- position: sticky; top: 0;
    <Main />
    <Footer /> <-- position: sticky; bottom: 0;
  </div>
</body>
```

---

I'm curious if this could be a bug where the browser isn't sure how to restore scroll position for an element that's getting recycled, or if there's some sort of internal scroll tracking in svelte-kit that isn't quite right. Seems like a fun problem to chew on.

**Comment by mglikesbikes** [comment]
Chiming in…

Seeing scroll-to-top behavior not working in iOS/safari, but fine on desktop/chrome.

For iOS/safari at least, it looks like a webkit regression, basically that `scroll-behavior: smooth` + `window.scrollTo` (programmatic scrolling) doesn't work: https://bugs.webkit.org/show_bug.cgi?id=238497 (Additional discussion: https://developer.apple.com/forums/thread/703294)

Temporary workaround I've implemented is a media query to reset `scroll-behavior`, e.g. `@media (max-width: 640px) { html { scroll-behavior: auto; } }` which makes `goto()` calls not dump me halfway down the subsequent page.

**Comment by petem-methods** [comment]
For us, the problem seems to happen consistently on mobile (iOS Chrome and Safari, at least) but less-frequently on desktop browsers. (No idea why it is intermittent on desktop.)

Our layout is similar to the one [nhunzaker](https://github.com/sveltejs/kit/issues/2733#issuecomment-1354105837) describes above. On desktop browsers, most of the time, the new pages load correctly, at the top. 

Here's a demo of the issue:

https://user-images.githubusercontent.com/101564068/214556754-91d4b602-6531-4c80-9439-6e65c58d69b0.mov

**Comment by dummdidumm** [comment]
Could one of the more recent reporters of this issue check if this also happens if you pin SvelteKit to version `1.2.1`? I want to make sure #8466 which was introduced in `1.2.2` isn't responsible for this.

**Comment by s3812497** [comment]
Most of the recently reported scrolling issues seems to have 2 different causes:

### 1. Setting `overflow: hidden` on the `html` element.

When using a scrolling area other than `html`, SvelteKit continues to use `window.scrollTo()` which will no longer work.
The various solutions posted here implement their own `scrollTo()` to a different element.

[Reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-cgdwrd?file=src/routes/styles.css)

### 2. iOS webkit `scroll-behavior: smooth` bug

Mentioned here https://github.com/sveltejs/kit/issues/2733#issuecomment-1383185510

Setting `scroll-behavior: smooth` on the `html` element causes programmatic scrolling to break.

Run the [reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-s5cxcd?file=src%2Froutes%2Fstyles.css,src%2Froutes%2F%2Bpage.svelte) with `npm run dev --host` and test the behaviour on an iOS / iPadOS.

**Comment by petem-methods** [comment]
Still occurring for us on `1.2.1`. (Actually, we were still on `^1.0.11` 😬 - now up-to-date at `^1.2.9`! )

We have a workaround inspired by https://github.com/sveltejs/kit/issues/2733#issuecomment-1341340679. Add a div on the top of our scrollable element (you could use an existing element if you have one appropriate) and use `scrollIntoView`:

    <div bind:this={top} />
    
    let top: HTMLElement;
    afterNavigate((nav) => {
      if (nav.type === "link") {
        top?.scrollIntoView();
      }
    });
    
We're checking `type === "link"` because we don't want to always scroll to top, for example when we're using `goto` with `noScroll`.

**Comment by dummdidumm** [comment]
> When using a scrolling area other than `html`, SvelteKit continues to use `window.scrollTo()` which will no longer work. The various solutions posted here implement their own `scrollTo()` to a different element.

Was wondering for a moment if it's feasible to check if `html` has `overflow: hidden`, and if so, traverse the dom a few elements (bf search depth 3), but that's a) not very performant b) can result in the wrong scrollbar getting scrolled. Imagine a navbar to the left at the same DOM depth than the main content. It gets found first and is scrolled when it should be the main content that's scrolled - that's worse than not scrolling at all.

**Comment by s3812497** [comment]
> Was wondering for a moment if it's feasible to check if `html` has `overflow: hidden`, and if so, traverse the dom a few elements (bf search depth 3), but that's a) not very performant b) can result in the wrong scrollbar getting scrolled. Imagine a navbar to the left at the same DOM depth than the main content. It gets found first and is scrolled when it should be the main content that's scrolled - that's worse than not scrolling at all.

I have a PR in the works that tries to address this problem. It might not be the right solution but I would appreciate any feedback on it.

The solution involves checking if `html` and `body` are scrollable, and provides a HTML attribute such as `data-sveltekit-main-scrollable` so the developer can easily tell SvelteKit where the main scrolling area is.

**Comment by AaronNBrock** [comment]
I'm here to report that I'm seeing this issue on the sveltekit sverdle demo (as well as my site) when I use `scroll-behavior: smooth` on firefox version `112.0.2 (64-bit)` when I use `scroll-behavior: smooth` on the `html`.

**Comment by s3812497** [comment]
> I'm here to report that I'm seeing this issue on the sveltekit sverdle demo (as well as my site) when I use `scroll-behavior: smooth` on firefox version `112.0.2 (64-bit)` when I use `scroll-behavior: smooth` on the `html`.

Which issue are you referring to? Is it `1. Setting overflow: hidden on the html element.` or `2. iOS webkit scroll-behavior: smooth bug`?

**Comment by AaronNBrock** [comment]
> Which issue are you referring to that causes scroll to break?
> 1. Setting overflow: hidden on the html element.
> 2. iOS webkit scroll-behavior: smooth bug.
> 
> If it's different from both of these, can you provide a reproducible?
> 
 
It functions the same way people are describing the iOS issue in that it only appears when I apply the ’scroll-behavior: smooth’.  I was able to reproduce it with a fresh install of the sverdle demo by only editing the style.css to add the smooth scrolling.

I'm away from my computer ATM, I'll edit this comment with a screen recording later today.

**Comment by s3812497** [comment]
> > Which issue are you referring to that causes scroll to break?
> > 
> > 1. Setting overflow: hidden on the html element.
> > 2. iOS webkit scroll-behavior: smooth bug.
> > 
> > If it's different from both of these, can you provide a reproducible?
> 
> It functions the same way people are describing the iOS issue in that it only appears when I apply the ’scroll-behavior: smooth’. I was able to reproduce it with a fresh install of the sverdle demo by only editing the style.css to add the smooth scrolling.
> 
> Edit: Here's the recording:
> 
> ![2023-04-30-12-26-06-firefox_u6CB](https://user-images.githubusercontent.com/25732263/235388063-85686838-6c9a-46f9-8ac4-70ff97737129.gif)

Thanks for the helpful feedback! I will try to investigate this as well.

**Comment by s3812497** [comment]
> It functions the same way people are describing the iOS issue in that it only appears when I apply the ’scroll-behavior: smooth’. I was able to reproduce it with a fresh install of the sverdle demo by only editing the style.css to add the smooth scrolling.

I can't seem to reproduce this on the same version of Firefox (macos). https://stackblitz.com/github/s3812497/sveltejs-kit-2733?file=README.md

Can you reproduce it using the repository I've shared, or provide a reproducible repository?

**Comment by AaronNBrock** [comment]
> Can you reproduce it using the repository I've shared, or provide your own reproducible repository?

@s3812497 I am able to reproduce it with the repo you linked above:

<details>
  <summary>Screen Recording</summary>
  
![2023-05-06-14-58-16-firefox_JqKG](https://user-images.githubusercontent.com/25732263/236642000-d430d677-e373-4b0d-a65d-ac6c66a7df53.gif)
  
</details>


I was also to reproduce it in my repository: https://github.com/AaronNBrock/sveltekit-scroll-test

With some playing around with it.  I'm noticing very consistent, yet odd behavior.  You'll see the site has 3 pages `/`, `/about` and `/about-other`.  

* It only does not scroll to the top when going from (`/` ⇾ `/about` or `/about-other/`)
* It does work properly when navigating between the about pages.
* It does work when navigating from about pages to the home page.

Also, this issue is only on Firefox (my version is 112.0.2 (64-bit) Windows 10) it works as expected on Chrome / Edge.

**Comment by crowdozer** [comment]
I bumped into this issue on my personal repo, using sveltekit `1.5.0`

here's a minimal reproducible sample https://github.com/crowdozer/svelte-kit-scroll-test

the gist is this inner "page" div never scrolls on navigation
```html
<div class="flex h-full flex-col overflow-auto">
	<header>
		<!-- header content -->
	</header>
	<div id="page" class="flex grow flex-col">
		<div class="grow">
			<!-- main page content here -->
		</div>
		<footer>
			<!-- footer content -->
		</footer>
	</div>
</div>
```

my workaround has been to put this in the root layout, now it works fine

```js
import { afterNavigate } from '$app/navigation';

afterNavigate(() => {
	document.getElementById('page')?.scrollTo(0, 0);
});
```

**Comment by jasongitmail** [comment]
Likely related, or maybe just more noticeable with this CSS:

```css
html {
  scroll-behavior: smooth;
}
```

Goal behavior:
1. On `/long-page`, clicking `#something` should scroll smoothly to that element. - Works!
2. On `/long-page`, scrolled near the bottom, click `/pageB`, and it _should_ jump immediately to top of `/pageB`. 

Actual behavior for #2:
-  When at bottom of `long-page`, clicking link to `/pageB` will show `/pageB` at the previous scroll position and then scroll up to the top smoothly.

**Comment by s3812497** [comment]
> Likely related, or maybe just more noticeable with this CSS:
> 
> 
> 
> ```css
> 
> html {
> 
>   scroll-behavior: smooth;
> 
> }
> 
> ```
> 
> 
> 
> Goal behavior:
> 
> 1. On `/long-page`, clicking `#something` should scroll smoothly to that element. - Works!
> 
> 2. On `/long-page`, scrolled near the bottom, click `/pageB`, and it _should_ jump immediately to top of `/pageB`. 
> 
> 
> 
> Actual behavior for #2:
> 
> -  When at bottom of `long-page`, clicking link to `/pageB` will show `/pageB` at the previous scroll position and then scroll up to the top smoothly. 

This behaviour and the solution are talked more about in this comment.
https://github.com/sveltejs/kit/pull/8724#issuecomment-1424436745

**Comment by jasongitmail** [comment]
Thanks @s3812497. I'd consider that a workaround, not a bug fix. But appreciate you pointing to that code.

**Comment by kiddailey** [comment]
> Thanks @s3812497. I'd consider that a workaround, not a bug fix. But appreciate you pointing to that code.

Agreed.   And it feels like a particularly hacky workaround for a bug -- it has to be included everywhere and doesn't really address the issue.

Some things I've noticed in my tests with Svelte 3.59.2 and Kit 1.22.3 (I can't update to 4.1.1 yet).

* Only Firefox is affected (works correctly in Chromium and Webkit based browsers)
* If the user clinks the link a second time after arriving on the destination page (e.g. the same footer link on the second page), The user is sent to the top of the page.  In other words, routing between pages maintains the scroll position for the initial page request only.
* Including anchor links does not fix the issue or work as expected.  For example, given a link to "/page#test" and an anchor "test" on destination page, the user is sent to the incorrect scroll position and not to the anchor's location.
* The length of the destination page as compared to the origin page has an impact on whether or not the issue occurs.  If the destination page is notably longer than the origin page, it will scroll to the top.  It is only when the destination page is of similar length or shorter than the origin page that it refuses to scroll to the top.

**Comment by Dan1ve** [comment]
I have a similar problem. When a navigate from the root page to a details page, the scroll position is not reset. 
My suspicion is that this may be caused by nested layouts, but I did not verify this.

I use the following snippet in my `+layout.svelte` to workaround this bug by forcing a re-render when the URL changes.

``` svelte
{#key $page.url}
<div bind:this={contentContainer} class="flex-1 overflow-auto">
	<slot />
</div>
{/key}
```

**Comment by eltigerchino** [comment]
> Most of the recently reported scrolling issues seem to be divided into 2 different causes:
> 
> ### 1. Setting `overflow: hidden` on the `html` element.
> When using a scrolling area other than `html`, SvelteKit continues to use `window.scrollTo()` which will no longer work. The various solutions posted here implement their own `scrollTo()` to a different element.
> 
> [Reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-cgdwrd?file=src/routes/styles.css)

Noting https://github.com/sveltejs/kit/pull/8723#issuecomment-1423522635 as a workaround. Perhaps we should document this as a solution?

**Comment by mkmiller6** [comment]
In my case, scroll behavior is only broken when navigating from root to another page, and only on the initial load. Refreshing the page will then scroll to the top. I'm running SvelteKit 2.3.2 and Svelte 4.2.8.

I tried many of the suggested fixes in this thread, but the only one that worked for me was using the following, or minor variants (e.g. binding to an element and scrollIntoView(), not checking nav type, etc.). The timeout is necessary, and setting the scroll behavior breaks it again.

```
afterNavigate((nav) => {
  if (nav.type === 'link') {
    setTimeout(() => {
      window.scrollTo(0,0);
    })
  }
})
```

However, that fix can result in a content flash that's a bit annoying on some loads due to the nature of setTimeout(). Inspired by that fix, the following also works for me and doesn't result in any content flashing. 

```
afterNavigate(async (nav) => {
  if (nav.type === 'link') {
    await tick();
    window.scrollTo(0, 0);
  }}
);
```

Seems odd, since as far as I can tell, svelteKit natively does something very similar (see [here](https://github.com/sveltejs/kit/blob/691ae7e021cb4bc324dcedc1d746948dbe81832b/packages/kit/src/runtime/client/renderer.js#L301C4-L301C4)).

**Comment by Opisek** [comment]
Still broken on Firefox. Seems to work on Chrome.

**Comment by mig-hub** [comment]
I still have this problem on both MacOS Safari 16.6 and Chrome 122.0.6261.69. But the weird thing is that it does not do it on every page. But it is consistent in the sense that a link to the "team" page would always keep the previous scroll position. It is really the previous scroll position because I have tried different scroll lengths to verify. The thing is that I cannot pin point what is similar is faulty pages that could cause this.

Since I have checked this thread, I have checked and my `html` element neither have overflow hidden or scroll-behavior smooth.

**Comment by eltigerchino** [comment]
Due to how large the scope of this thread has become, it’s difficult to understand how your app’s scrolling is broken, and what is causing it. 

It would be a great help for future reports to include a description of the expected behaviour, the current behaviour, and a minimal reproduction in the form a code repository so that we can diagnose the root cause.

**Comment by engageintellect** [comment]
Same issue. I haven't found any working solution/hack/work-around.


./package.json
```
	"devDependencies": {
		"@iconify/json": "^2.2.187",
		"@playwright/test": "^1.28.1",
		"@sveltejs/adapter-auto": "^3.0.0",
		"@sveltejs/kit": "^2.0.0",
		"@sveltejs/vite-plugin-svelte": "^3.0.0",
		"@types/eslint": "^8.56.0",
		"@typescript-eslint/eslint-plugin": "^7.0.0",
		"@typescript-eslint/parser": "^7.0.0",
		"@zerodevx/svelte-toast": "^0.9.5",
		"autoprefixer": "^10.4.16",
		"daisyui": "^4.7.2",
		"eslint": "^8.56.0",
		"eslint-config-prettier": "^9.1.0",
		"eslint-plugin-svelte": "^2.36.0-next.4",
		"postcss": "^8.4.32",
		"postcss-load-config": "^5.0.2",
		"prettier": "^3.1.1",
		"prettier-plugin-svelte": "^3.1.2",
		"prettier-plugin-tailwindcss": "^0.5.9",
		"svelte": "^5.0.0-next.1",
		"svelte-check": "^3.6.0",
		"tailwindcss": "^3.3.6",
		"tslib": "^2.4.1",
		"typescript": "^5.0.0",
		"unplugin-icons": "^0.18.5",
		"vite": "^5.0.3",
		"vitest": "^1.2.0"
	},
	"type": "module",
	"dependencies": {
		"@tailwindcss/line-clamp": "^0.4.4",
		"chart.js": "^4.4.2",
		"d3-scale": "^4.0.2",
		"svelte-add": "2024.2.16-0.0"
	}
}
```

**Comment by khromov** [comment]
@mig-hub 

> Here is what I can confirm though: It is related to the fact that I have a main tag that has min-height at 100vh coupled with the fact that I have a footer below.

I had a very similar problem and my issue was that I wasn't actually scrolling in the top level page but inside my content div. To fix this, I bound the content div to a variable, and then invoked `scrollTop = 0` on it during onNavigate. In my case I had to use onNavigate to work properly with the Page Transitions API but you can probably use either beforeNavigate as well if you don't have any Page Transitions.

```html
<script>
	import { onNavigate } from '$app/navigation';
	let contentDiv;

	onNavigate((navigation) => {
		return new Promise((resolve) => {
			const transition = document.startViewTransition(async () => {
				if(contentDiv) {
					// Fix scroll
					contentDiv.scrollTop = 0;
				}
				resolve();
				await navigation.complete;
			});
		});
	});
</script>

<div class="header">...</div>

<div class="content" bind:this={contentDiv}>
	<slot />
</div>

<div class="footer">...</div>
```

**Comment by MoritzLoewenstein** [comment]
In this case it broke for me on firefox:
1) scroll-behaviour: smooth on html element
2) click on a link with a hash value -> scrolling to the hash element works
3) click on a link without a hash value -> page is not scrolled to top, does not change at all
4) click on the same link a second time -> page will scroll to top

When removing scroll-behaviour, it will work.

**Comment by elucidsoft** [comment]
The problem is not really related to SvelteKit. If you have your using overflow-x-scroll or overflow-x-auto or h-screen (tailwind classes you can lookup the css styles as it also applies) then you will notice this behavior. If you remove those, the behavior returns to normal. This is a known side effect of using these on outer wrappers in CSS.  You need to change the outer structure of your HTML to fix the issue.

**Comment by etczrn** [comment]
I don't know this will help but I got this solution.
``` typescript
// +layout.svelte -- I put the code inside layout svelte so that it can affect every page.

  // 1. Maka a variable that stores old pathname.
  let pathname = '';
  // 2. When the layout page mount, store the pathname.
  onMount(() => {
    pathname = $page.url.pathname;
  });

  beforeNavigate(() => {
    pathname = $page.url.pathname;
  });

  afterNavigate(() => {
    if (pathname === $page.url.pathname) return;
    window.scrollTo({ top: 0, behavior: 'auto' });
  });
```

**Comment by engageintellect** [comment]
> Same issue. I haven't found any working solution/hack/work-around. Sadly, none of the solutions mentioned in here seemed to work for me either.
> 
> I should also mention that I am unable to reproduce this issue in a desktop browser, even if I make the viewport short enough to make the page scroll-able, and scroll down before navigating to the next link. This issue for me only seems to be happening on mobile browsers.
> 
> ./package.json
> 
> ```
> 	"devDependencies": {
> 		"@iconify/json": "^2.2.187",
> 		"@playwright/test": "^1.28.1",
> 		"@sveltejs/adapter-auto": "^3.0.0",
> 		"@sveltejs/kit": "^2.0.0",
> 		"@sveltejs/vite-plugin-svelte": "^3.0.0",
> 		"@types/eslint": "^8.56.0",
> 		"@typescript-eslint/eslint-plugin": "^7.0.0",
> 		"@typescript-eslint/parser": "^7.0.0",
> 		"@zerodevx/svelte-toast": "^0.9.5",
> 		"autoprefixer": "^10.4.16",
> 		"daisyui": "^4.7.2",
> 		"eslint": "^8.56.0",
> 		"eslint-config-prettier": "^9.1.0",
> 		"eslint-plugin-svelte": "^2.36.0-next.4",
> 		"postcss": "^8.4.32",
> 		"postcss-load-config": "^5.0.2",
> 		"prettier": "^3.1.1",
> 		"prettier-plugin-svelte": "^3.1.2",
> 		"prettier-plugin-tailwindcss": "^0.5.9",
> 		"svelte": "^5.0.0-next.1",
> 		"svelte-check": "^3.6.0",
> 		"tailwindcss": "^3.3.6",
> 		"tslib": "^2.4.1",
> 		"typescript": "^5.0.0",
> 		"unplugin-icons": "^0.18.5",
> 		"vite": "^5.0.3",
> 		"vitest": "^1.2.0"
> 	},
> 	"type": "module",
> 	"dependencies": {
> 		"@tailwindcss/line-clamp": "^0.4.4",
> 		"chart.js": "^4.4.2",
> 		"d3-scale": "^4.0.2",
> 		"svelte-add": "2024.2.16-0.0"
> 	}
> }
> ```

Same here. I am only able to reproduce in chrome for iOS. Everything works as expected in Safari and on desktop browsers of all viewport widths and setting the device to iphone in inspector settings.

I can't seem to fix a hack or work around. It's like chrome on mobile just wants to retain the scroll position of the previous page no matter what.

I remember running into this problem 6 months or so ago, and finding a fix. But I can't, for the life of me remember what I did.

**Comment by code-sanchu** [comment]
The `afterNavigate` workaround works for me but with a `timeout`:

```
afterNavigate(() => {
    setTimeout(() => {
        window.scrollTo(0, 0);
    }, 50);
});
```

**Comment by Opisek** [comment]
@rubenesque-code You might not have considered the case where you don't want to scroll to the very top, so when you press links with url fragment set (`https://example.com/page#fragment`). Does my workaround above work for you?

**Comment by mig-hub** [comment]
@khromov Thank you so much for your suggestion and taking the time to provide a snippet! 

Sorry I did not see your reply until now. It did not show in the unread messages for some reasons. I will definitely try that when going back to the project I was talking about.

**Comment by w3rafu** [comment]
On mobile browsers, a common layout structure involves setting `html` and `body` tags to `height: 100%` and `overflow: hidden`. This disables the browser's default document scrolling, with content instead scrolling within an internal wrapper element.

SvelteKit attempts to preserve scroll position during navigation. However, because `overflow: hidden` is applied to `html` and `body,` SvelteKit preserves the (essentially non-existent) scroll position of the document `body`, not the scroll position of the internal, scrollable wrapper. This means that if a user navigates from a link in the middle of the wrapper's Y position, the new page will appear to render with the wrapper scrolled to the same Y position as before.

Resetting the wrapper's scroll position after navigation, using techniques like `afterNavigate,` can lead to a "scroll to top" animation or a delay of around 350ms, where the user briefly sees the content at the incorrect scroll position before it's corrected.

Is this behavior primarily a limitation or design choice within the SvelteKit framework, or is it fundamentally a layout structure problem arising from the interaction of single-page application navigation?

There is an assumption that the body is the primary scroll container and SvelteKit or the browsers are not ready to preserve the scroll position of a different element during navigation. 

Hopefully, a future version of Sveltekit would include a mechanism to identify and/or persist the scroll position of a different element during navigation.

**Comment by nmzein** [comment]
Can confirm that I've been having this issue too recently for the same reason listed by @w3rafu. Hope its fixed soon.

**Comment by nikonikoniko** [comment]
For me it was broken in firefox and chrome in newest svelte / kit. Navigating to new pages didn't change scroll positions - land somewhere at the bottom of a new page.

@MoritzLoewenstein 's comment helped:

> In this case it broke for me on firefox:
> When removing scroll-behaviour, it will work.

```css
html {
  scroll-behavior: unset !important;
}
```

Adding this fixed the issue for me, while unfortunately disabling smooth-scroll from anchor links.  Luckily this behaviour isn't necessary for me.

**Comment by eltigerchino** [comment]
> For me it was broken in firefox and chrome in newest svelte / kit. Navigating to new pages didn't change scroll positions - land somewhere at the bottom of a new page.
> 
> [@MoritzLoewenstein](https://github.com/MoritzLoewenstein) 's comment helped:
> 
> > In this case it broke for me on firefox:
> > When removing scroll-behaviour, it will work.
> 
> html {
>   scroll-behavior: unset !important;
> }
> 
> Adding this fixed the issue for me, while unfortunately disabling smooth-scroll from anchor links. Luckily this behaviour isn't necessary for me.

Any chance you could share a minimal reproduction with us?

**Comment by nikonikoniko** [comment]
> Any chance you could share a minimal reproduction with us?

Unfortunately I noticed I had the human error of having had set `scroll-behavior: smooth` myself at another point in the CSS.  Would it still be helpful for a minimal reproduction of it not working when `scroll-behavior` is smooth, or is this a known issue?

**Comment by eltigerchino** [comment]
> > Any chance you could share a minimal reproduction with us?
> 
> Unfortunately I noticed I had the human error of having had set `scroll-behavior: smooth` myself at another point in the CSS. Would it still be helpful for a minimal reproduction of it not working when `scroll-behavior` is smooth, or is this a known issue?

It would definitely be helpful if you provided a reproduction and explained the current and expected behaviour. I don't think smooth scrolling should prevent the page scroll position from being reset, so it's a real issue if it is doing that.

**Comment by s626ch** [comment]
> On mobile browsers, a common layout structure involves setting `html` and `body` tags to `height: 100%` and `overflow: hidden`. This disables the browser's default document scrolling with content instead scrolling within an internal wrapper element.
> 
> SvelteKit attempts to preserve scroll position during navigation. However, because `overflow: hidden` is applied to `html` and `body,` SvelteKit preserves the (essentially non-existent) scroll position of the document `body`, not the scroll position of the internal, scrollable wrapper. This means that if a user navigates from a link in the middle of the wrapper's Y position, the new page will appear to render with the wrapper scrolled to the same Y position as before.
> 
> Resetting the wrapper's scroll position after navigation, using techniques like `afterNavigate,` can lead to a "scroll to top" animation or a delay of around 350ms, where the user briefly sees the content at the incorrect scroll position before it's corrected.
> 
> Is this behavior primarily a limitation or design choice within the SvelteKit framework, or is it fundamentally a layout structure problem arising from the interaction of single-page application navigation?
> 
> There is an assumption that the body is the primary scroll container and SvelteKit or the browsers are not ready to preserve the scroll position of a different element.
> 
> Hopefully, a future version of Sveltekit would include a mechanism to identify and/or persist the scroll position of a custom element during navigation.

this is my current setup and how i've gotten used to making things for what feels like ever, can't find any workaround that isn't a mess

**Comment by MatthiasKunnen** [comment]
This is my current Svelte5 approach on how to scroll-to-top on navigate but restore the scroll on back button:

```ts
let scrollContainer = $state<HTMLElement>(); // Add bind:this={scrollContainer} on your scroll container
let lastScrollRestoreTime = 0;

afterNavigate(() => {
    if (scrollContainer === undefined) {
        return;
    }

    if (Date.now() - lastScrollRestoreTime > 500) {
        // Only scroll to top if no restore (back button) has been performed.
        // This prevents content from flashing on back button where first, a scroll
        // to top is performed, and then an immediate scroll to content.
        scrollContainer.scrollTop = 0;
    }
});

export const snapshot: Snapshot<number> = {
    capture: () => {
        return scrollContainer?.scrollTop ?? 0;
    },
    restore: (value) => {
        if (scrollContainer === undefined) {
            return;
        }
        // Executed before afterNavigate, see https://github.com/sveltejs/kit/issues/10823
        lastScrollRestoreTime = Date.now()
        scrollContainer.scrollTop = value
    },
};
```

This could probably be turned into an Action or Attachement for reuse.

**Comment by abj360** [comment]
Hi! I'm a student from CodePath working on open source projects, and I'd like to work on this scroll position regression. I've reviewed the issue and understand the problem: navigating between pages no longer resets the scroll to the top after next-192 → next-193. Before I dive into the codebase, I have a couple of initial questions:
1. Is this still an open issue? I want to make sure it's not already been claimed.
2. Do you have any pointers on where the scroll reset logic lives in the router code (I'm guessing packages/kit/src/runtime/client/)?
3. Should I focus on reproducing the regression in a minimal test case first, or would it be more helpful to bisect the commit history between those versions?
Thanks for any guidance!!
