### ISSUE TITLE
When there is not title in the page(inside svelte:head in svelte page component in the src/routes folder) the browser shows title for the last page that had it

### ISSUE THREAD

**Issue by PH4NTOMiki** [sveltejs/kit#3305]
### Describe the bug

So if a Svelte page doesn't have a title in svelte:head, the browser shows the title for the last page that did have it, and in "normal" sites in this case browser only shows the URL of the page as the browser tab title, and if you reload that URL in the browser it would be inconsistent, so the quick fix would be to check: 
If there is no title for the page when navigating, just set `document.title = '';` and that would fix this.

### Reproduction

[https://stackblitz.com/edit/sveltekit-7mnqkm?file=src/routes/page2.svelte](https://stackblitz.com/edit/sveltekit-7mnqkm?file=src/routes/page2.svelte)

open this link(open in new window in stackblitz), click "Go to Page2" and the browser tab title would still be "Page 1" from the previous link.

### System Info

```shell
latest sveltekit
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
> just set `document.title = '';` and that would fix this.

Duplicating my comment from #3347: 

---

Unfortunately this creates a bug — if (say) you have a `<title>Foo</title>` in `foo/__layout.svelte`, then clicking between `/foo/bar` and `/foo/baz` will cause the title to be removed (unless the child pages each have a `<title>` of their own).

To my mind this bug is worse than the bug being fixed here, since having a title in a layout that applies to its child pages might be deliberate, and it's worse to interfere with deliberate behaviour than to have buggy behaviour that results from an oversight.

**Comment by biltongza** [comment]
In my case - I have my title set in app.html which I want to be the "default" title, and then sub pages can modify it, but if I navigate away from the page it should revert to the "default" title or whatever title the new page has.

**Comment by PH4NTOMiki** [comment]
@Rich-Harris I understand that, and I'm guessing it's really hard to do some "inheritance" for the titles, but if it is possible that would be great, to look up in the preceding layout components and if there isn't any title in them, and there is no title in the current page component to set it to empty string.

**Comment by Rich-Harris** [comment]
I'm going to close this as I think it's fundamentally impossible to solve at a framework level. The `title` isn't a stack that we can rewind when a component is unmounted, and any attempt to treat it like one is going to run into edge cases. The simple answer is that you do need to specify a title. 

One alternative approach would be to have this in your root layout...

```svelte
<script>
  import { page } from '$app/stores';
</script>

<svelte:head>
  <title>{$page.stuff.title || 'untitled page'}</title>
</svelte:head>
```

...then return a [`stuff`](https://kit.svelte.dev/docs#loading-output-stuff) object from page load functions (or intermediate layouts):

```svelte
<script context="module">
  export function load() {
    return {
      // ...
      stuff: { title: 'hello world' }
    };
  }
</script>
```

That way it will fall back to 'untitled page', or you could throw an error if a page neglected to set a title.

**Comment by patricknelson** [comment]
Noob here. For me it was just easier to take the component-based approach. 

Unfortunately it doesn't really solve the problem of what to do if a title is missing for a particular page/layout, but... if you're gonna have to repeat yourself, may a well go with the simplest and lowest common denominator... components!

```svelte
<script>
  export let title = '';
  let fullTitle = (title ? title + ' - ' : '') + 'My Website';
</script>

<svelte:head>
  <title>{fullTitle}</title>
</svelte:head>
```

And then the typical import.

```svelte
<script>
  import PageTitle from '$components/PageTitle.svelte';
</script>

<PageTitle title="Test page"/>

<p>Example page.</p>
```
