### ISSUE TITLE
+layout.svelte <Layout> was created with unknown prop 'data'

### ISSUE THREAD

**Issue by kuchaguangjie** [sveltejs/kit#6095]
### Describe the bug

I saw following warning in chrome devtools:

```
+layout.svelte <Layout> was created with unknown prop 'data'
```

The code is like this:
```
<script>
  import {afterUpdate} from 'svelte';
  // ..

  let loginNick
  afterUpdate(async () => {
    loginNick = sessionStorage.getItem('nick'); // The warning is on this line,
  });
</script>
```
Any idea ?

### Reproduction

Just add code above, and refresh the page, and in chrome devtools, could see the warning.

### System Info

```shell
System:
    OS: Linux 5.14 Linux Mint 20.1 (Ulyssa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 250.66 MB / 15.55 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.17.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.422 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.8
```

### Severity

Not urgent.

**Comment by Conduitry** [comment]
You're on Kit `1.0.0-next.422`. This should already be fixed on the latest version - https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md - Please make sure you are using the latest version before opening issues.

**Comment by kuchaguangjie** [comment]
Cool, upgrade to `1.0.0-next.427`, then there is no such warning.

**Comment by kuchaguangjie** [comment]
@Conduitry 
It seems there warning can still pop-out when start in dev mode:
- If I refresh the page, these warning are not shown.
- But, If I change some code, and vite did hot update, then such warning seems still shown, e.g 
```
[vite] hot updated: /src/components/YesNoDialog.svelte
+layout.svelte:15 <Layout> was created with unknown prop 'data'
+layout.svelte:32 <Layout> was created with unknown prop 'data'
+page.svelte:24 <Page> was created with unknown prop 'data'
+page.svelte:24 <Page> was created with unknown prop 'errors'
```

**Comment by peterpeterparker** [comment]
With `"@sveltejs/kit": "^1.0.0-next.468"` git the warning too. I've got the feeling it has to do with the fact that might layout use `await`

```
{#await i18n.init() then}
  <slot />
{/await}
```
