### ISSUE TITLE
Not found /_app/immutable/assets/xxx

### ISSUE THREAD

**Issue by kamerat** [sveltejs/kit#9089]
### Describe the bug

We're hosting sveltekit with SSR in a Docker container that's hosted in azure. We have datadog to track errors and we tend to see about 3 to 30 of these 404's a day on our small-medium site.

We played around with azure cdn cache, but when we enabled this, the errors really came to show, so we disabled the azure cache. When doing so, it went back to it's normal occurance.

This issue is the same as this question posted a while ago; https://github.com/sveltejs/kit/discussions/7057
 

Example error for a 404 asset:
```
Error: Not found: /_app/immutable/assets/_layout-c5c8ebf1.css
at resolve (file:///app/server/index.js:2276:18)
at resolve (file:///app/server/index.js:2163:34)
at Object.handle (file:///app/server/chunks/hooks.server.js:379:10)
at runMicrotasks (<anonymous>)
at runNextTicks (node:internal/process/task_queues:61:5)
at processImmediate (node:internal/timers:437:9)
at async respond (file:///app/server/index.js:2161:22)
at async Array.ssr (file:///app/handler-393b2283.js:1102:3)
```

What might be the cause of this type of error, Is it just something that happenes when document is out of sync with assets, or is it something we can do to keep this from happening?

![Screen Shot 2023-02-17 at 12 36 28 PM](https://user-images.githubusercontent.com/11461961/219644405-f429b759-7531-40c2-9b30-e1d082b4d6a6.png)

### Reproduction

-

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 347.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.85 
    @sveltejs/kit: ^1.0.1 => 1.0.1 
    svelte: ^3.44.0 => 3.55.0 
    vite: ^4.0.3 => 4.0.3
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
My guess: You deploy a new version, the user is still using the old version and doing a navigation to a not-yet-loaded page where they need to request an asset (JS file or whatever), which then fails. It's more visible when turning CDN off since the CDN is caching the outdated assets from your previous deployment for a while.
SvelteKit should do a full-page reload if it sees that a navigation wasn't successful. I'm not sure if this also applies to CSS files though.

**Comment by Rich-Harris** [comment]
Something we should document: you can detect version changes and proactively opt in to full page reloads by setting a `version.pollInterval` in your config and using it to disable the client-side router:

```svelte
<!-- src/routes/+layout.svelte -->
<script>
  import { updated } from '$app/stores';
</script>

<main data-sveltekit-reload={$updated ? '' : 'off'}>
  <slot />
</main>
```

**Comment by snuffyDev** [comment]
@Rich-Harris https://github.com/sveltejs/kit/issues/9089#issuecomment-1435370289

Firstly, excuse me for my ignorance, but I've been getting similar errors on Sentry for an app at work, and I've been tasked with investigating it (3 weeks in, currently writing a 3rd Notion document :face_exhaling:). Seeing your response gave me a few questions about this.

The docs for the [`updated` config option](https://kit.svelte.dev/docs/configuration#version) currently states:

> Not all navigations will result in an error though, for example if the JavaScript for the next page is already loaded.

1. Would a pre-rendered SPA (using static adapter) potentially be one of the cases where a navigation wouldn't trigger a full-page reload?
2. Would it be safe to assume that Sentry (and similar platforms) would be reporting a lot of false positives? 
	- Example: User is on `https://my-fake.app/`, they navigate to `https://my-fake.app/profile`. Although the page loads perfectly fine, Sentry still reports that there was an error.

I appreciate any insight, and if this wasn't the appropriate place to ask, I can create a Discussion. This potentially could save me a lot of time, thank you!

**Comment by dummdidumm** [comment]
1. Not necessarily. If some assets are not loaded yet, and they are required for the next page you're about to navigate to, you'll also run into the 404 in case of a new version
2. Yes, everytime you deploy a new version you'll likely get some false positives in the sense that there are errors reported but your users likely won't notice anything

**Comment by kristjanmar** [comment]
> I think it is JS files only, but that's fine since any pages that are loaded for client-side nav also have a JS portion. When one of these requests fails with a 404, SvelteKit will automatically request `/_app/version.json`, and if that's change, it will turn the navigation into a full page reload rather that a client-side SPA navigation.

> Something we should document: you can detect version changes and proactively opt in to full page reloads by setting a `version.pollInterval` in your config and using it to disable the client-side router:
> 
> ```svelte
> 
> <script>
>   import { updated } from '$app/stores';
> </script>
> 
> <main data-sveltekit-reload={$updated ? '' : 'off'}>
>   <slot />
> </main>
> ```

This is a bit confusing. Is it handled automatically like Conduitry suggested or is it required to implement the code that Rich Harris suggested? What's the point of the code snippet if it's already handled by SvelteKit?

I've been getting a bunch of errors related to this in Sentry and they are definitely real errors because I've gotten many emails from users that have gotten them.

**Comment by Rich-Harris** [comment]
That's odd — those are the errors that usually lead to a request for `version.json` followed by a reload. Unless `version.json` is somehow the same before and after the redeploy?

**Comment by kevinrenskers** [comment]
> Something we should document: you can detect version changes and proactively opt in to full page reloads by setting a `version.pollInterval` in your config and using it to disable the client-side router:
> 
> ```svelte
> 
> <script>
>   import { updated } from '$app/stores';
> </script>
> 
> <main data-sveltekit-reload={$updated ? '' : 'off'}>
>   <slot />
> </main>
> ```

I'm also trying to extremely common `Failed to fetch dynamically imported module` error and came across this issue, and this comment from @Rich-Harris. Sadly using this code I get the following error in my console:

`Error: Cannot subscribe to 'updated' store on the server outside of a Svelte component, as it is bound to the current request via component context. This prevents state from leaking between users.For more information, see https://kit.svelte.dev/docs/state-management#avoid-shared-state-on-the-server`

Looking at https://kit.svelte.dev/docs/modules#$app-stores-updated it didn't really make it clearer to me how to use this properly.

**Comment by dummdidumm** [comment]
I don't get this error given that code snippet. Please open a separate issue with a reproduction repo if the issue persists.

**Comment by kevinrenskers** [comment]
I haven't seen it anymore after that one time, no idea what caused it 🤷‍♂️

**Comment by magic-thomas** [comment]
Same error here. 

<img width="764" alt="Screen Shot 2023-04-24 at 1 18 00 AM" src="https://user-images.githubusercontent.com/69987486/233851837-50c3ff20-0f0c-4290-b4d3-2490554f6285.png">

**Comment by magic-thomas** [comment]
> 



> Something we should document: you can detect version changes and proactively opt in to full page reloads by setting a `version.pollInterval` in your config and using it to disable the client-side router:
> 
> ```svelte
> 
> <script>
>   import { updated } from '$app/stores';
> </script>
> 
> <main data-sveltekit-reload={$updated ? '' : 'off'}>
>   <slot />
> </main>
> ```

<img width="932" alt="Screen Shot 2023-04-24 at 1 50 40 AM" src="https://user-images.githubusercontent.com/69987486/233853860-7a156710-4b80-4629-8267-da297b87d396.png">


After following this, I got all errors from js file. 

So I made trick. I exchanged two values.

```svelte
<main data-sveltekit-reload={$updated ? 'off' : ''}>
```

But it showed same results. 

I don't have deep knowledge, so  just wish somebody can solve this issue.

**Comment by snuffyDev** [comment]
Just figured out what exactly is changing, all of the files Kit touches / creates *always* have a different hash, regardless of if Vite's hashes would stay the same. Here's a commit on a repro -> https://github.com/snuffyDev/sveltekit-hash-gen-repro/commit/0343f726a29ddda16263b1e938be3d0adcab8301

To reproduce yourself locally:
- clone and install.
- run a build (save the contents of the `singletones.xxxx.js` file, for example, somehow)
- run a build again
- diff the two `singleton` files.

The hashes change, and even the actual output does as well, even though the contents haven't? Is due to Vite building with rollup, or something?

Here's a video showing what Vite's behavior looks like when building a library I work on (contents of the files haven't changed between builds -> hashes stay the same): 

https://user-images.githubusercontent.com/72365477/236735437-3ccbe3b6-5b84-435f-88f7-fc8bc172e3eb.mp4

**Comment by gtm-nayan** [comment]
@snuffyDev Are you setting a version name explicitly in your svelte config? Otherwise it defaults to the timestamp and as such every build will have a different version number embedded in it which will change the hashes for most chunks.

**Comment by snuffyDev** [comment]
> @snuffyDev Are you setting a version name explicitly in your svelte config? Otherwise it defaults to the timestamp and as such every build will have a different version number embedded in it which will change the hashes for most chunks.

Midnight Airhead moment :skull:, slipped my mind that `version.name` existed.

**Comment by wobedi** [comment]
@gtm-nayan Assuming default svelte version.name config (i.e. timestamp of build), is it therefore intended that the hashes for most chunks change on every deploy, regardless of code changes?
Because that seems to lead to "overeager invalidation" and thus to more "user agent tries to fetch invalidated chunk and crashes" issues? 
Or am I missing something?

**Comment by gtm-nayan** [comment]
> is it therefore intended that the hashes for most chunks change on every deploy, regardless of code changes?

We certainly don't want that to happen, but I don't really see any other sane default that we can put either. We're assuming people won't usually deploy often without code changes. (css, js, even strings inside your js/svelte files *are* code changes).

> user agent tries to fetch invalidated chunk and crashes
The router regularly polls the version file to check if it has been updated and falls back to native navigation if it has. And you can use the snippet that Rich provided above in case you make use of a lot of dynamic imports.
https://github.com/sveltejs/kit/blob/51c0b3cdccf3545892459f196bc71740481bcff8/packages/kit/src/runtime/client/client.js#L735

Users should probably base their versions on some version control identifier if available but the framework can't assume its presence.

We could maybe try to use a hash of the vite manifest, but that has a chicken and egg problem of its own.

**Comment by Fasteroid** [comment]
I get this without fail every time for github pages.  Why?

**Comment by SubhamPramanik** [comment]
Hey folks. We're facing this issue as well. Somehow it's originating from Sentry. Is there a workaround for this? Some of our users are affected.

**Comment by eltigerchino** [comment]
@Fasteroid @SubhamPramanik if you can share a reproduction, it would help with diagnosing the issue.

**Comment by jycouet** [comment]
@SubhamPramanik , what version are you running would help as well.

**Comment by tiwarishankar** [comment]
hey @jycouet right now we are using   "@sveltejs/kit": "^1.20.5", and error that is coming for us is attached below 
@SubhamPramanik 

<img width="774" alt="Screenshot 2023-11-01 at 3 29 29 PM" src="https://github.com/sveltejs/kit/assets/71537738/f9d98957-ba93-41de-83fa-fc9017f83ab5">

**Comment by SubhamPramanik** [comment]
@jycouet @eltigerchino 
We aren't able to fully reproduce the issue at will on our side. It happens pretty randomly and we can see the same in user session replays as well. Here are some pointers that might be relevant, as this issue started happening after we made the following changes:
- We recently moved our Sveltekit app to a Docker container. I've shared the Dockerfile [1] for it below.
- We were running the app as `vite dev --host` but now we're running it as `node build/index.js` after `vite build`.
- I'm not sure if this is relevant but with `vite dev --host` I saw significant memory consumption in the pod and the app would crash pretty frequently with the following error [2], which led us to use `node build/index.js`, post which the resource consumption wasn't as much.
- Also sharing our package.json for version checks and dependencies.
- The issue gets resolved as soon as we clear the cache. So I'm assuming the issue is somewhat related to cache reference. 


[1] Dockerfile
```
# Build Stage
FROM node:18-buster AS build

# Install Doppler
ARG DOPPLER_AUTH_TOKEN
ARG DOPPLER_CONFIG
ENV DOPPLER_TOKEN ${DOPPLER_AUTH_TOKEN}
ENV DOPPLER_CONFIG ${DOPPLER_CONFIG}

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg && \
    curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | apt-key add - && \
    echo "deb https://packages.doppler.com/public/cli/deb/debian any-version main" | tee /etc/apt/sources.list.d/doppler-cli.list && \
    apt-get update && \
    apt-get -y install doppler

WORKDIR /app
COPY . .
RUN doppler setup -p chat-collectiv --config $DOPPLER_CONFIG

# Install Python, make, and g++ for node-gyp
RUN apt-get install -y python3 make g++ && ln -sf python3 /usr/bin/python

# Install dependencies
RUN npm install

# Build the package
RUN npm run build

# Expose port
EXPOSE 5173
EXPOSE 3000

CMD ["npm", "run", "prod"]
```
[2] Error image
![WhatsApp Image 2023-10-25 at 7 28 07 PM](https://github.com/sveltejs/kit/assets/22225798/095f4dd6-fa06-4a37-a127-34e3240525d2)

[3] package.json
```
{
  "name": "frontend_app",
  "private": "true",
  "version": "0.0.1",
  "scripts": {
    "dev": "doppler secrets download --no-file --format env > .env && vite dev --host",
    "build": "doppler secrets download --no-file --format env > .env &&  vite build",
    "preview": "vite preview --port 3000",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
    "generate:sitemap": "node generate-sitemap.js",
    "prod": "doppler secrets download --no-file --format env > .env && node build/index.js"
  },
  "devDependencies": {
    "@lottiefiles/svelte-lottie-player": "^0.3.0",
    "@neoconfetti/svelte": "^1.0.0",
    "@sveltejs/adapter-auto": "^2.0.0",
    "@sveltejs/kit": "^1.20.5",
    "@sveltestack/svelte-query": "^1.6.0",
    "@tsconfig/svelte": "^4.0.1",
    "@types/cookie": "^0.5.1",
    "@types/gtag.js": "^0.0.13",
    "@types/js-cookie": "^3.0.3",
    "autoprefixer": "^10.4.14",
    "axios": "^1.4.0",
    "dotenv": "^16.1.4",
    "linkifyjs": "^4.1.1",
    "node-sass": "^8.0.0",
    "postcss": "^8.4.23",
    "postcss-load-config": "^4.0.1",
    "prismjs": "^1.29.0",
    "socket.io-client": "^4.6.1",
    "svelte": "^4.0.0",
    "svelte-check": "^3.4.3",
    "svelte-intersection-observer": "^0.10.0",
    "svelte-preprocess": "^5.0.3",
    "svelte-transition": "^0.0.7",
    "tailwindcss": "^3.3.1",
    "tslib": "^2.4.1",
    "typescript": "^5.0.0",
    "vite": "^4.3.6"
  },
  "type": "module",
  "dependencies": {
    "@sentry/sveltekit": "^7.69.0",
    "@sveltejs/adapter-node": "^1.3.1",
    "dom-to-image": "^2.6.0",
    "downloadjs": "^1.4.7",
    "file-saver": "^2.0.5",
    "html-to-image": "^1.11.11",
    "html2canvas": "^1.4.1",
    "js-cookie": "^3.0.5",
    "modern-screenshot": "^4.4.28",
    "moment": "^2.29.4",
    "noisejs": "^2.1.0",
    "path": "^0.12.7",
    "sass": "^1.63.6",
    "sitemap": "^7.1.1",
    "statsig-js": "^4.39.2",
    "svelte-click-outside": "^1.0.0",
    "svelte-french-toast": "^1.2.0",
    "svelte-infinite-scroll": "^2.0.1",
    "three": "^0.154.0",
    "troika-three-text": "^0.48.0-unicode.3",
    "uuid": "^9.0.0",
    "vite-plugin-string": "^1.2.1"
  }
}
```

**Comment by eltigerchino** [comment]
@SubhamPramanik thank you for sharing that info. Is it possible for you to also share what files are being cached / how the cache is setup? This seems to be a common factor with regards to the issue author's description

**Comment by Fasteroid** [comment]
Thank you for re-opening.  The only reason I'm here is because nobody has answered #9381, so I'm forced to use CSR just to have client-side javascript.

After clearing my head for 2 weeks, I realize now the issue is that since I'm hosting on Github Pages but using the legacy way of deploying a branch, SvelteKit's guess that the chunks are at `https://github.com/Fasteroid/svelte-portfolio/` is wrong; they're actually at `https://github.com/Fasteroid/svelte-portfolio/tree/gh-pages`.

Seems this was likely user error.  What's the correct way to fix this?

**Comment by eltigerchino** [comment]
> After clearing my head for 2 weeks, I realize now the issue is that since I'm hosting on Github Pages but using the legacy way of deploying a branch, SvelteKit's guess that the chunks are at `https://github.com/Fasteroid/svelte-portfolio/` is wrong; they're actually at `https://github.com/Fasteroid/svelte-portfolio/tree/gh-pages`.
> 
> Seems this was likely developer error on my part. What's the correct way to fix this?

You’ll want to configure the `paths.base` setting to match wherever your files live at.

https://kit.svelte.dev/docs/configuration#paths

See https://kit.svelte.dev/docs/adapter-static#github-pages for more comprehensive info. I’ve just updated it.

**Comment by SubhamPramanik** [comment]
Hey @eltigerchino, I looked into our setup and I don't see any caching config on our side. My best guess would be that we're using the default caching setup provided by Vite/SvelteKit.

Here in the vite.config.ts:
```
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig, loadEnv } from "vite";
import string from "vite-plugin-string";
import { sentrySvelteKit } from '@sentry/sveltekit'

export default ({ mode }: any) => {
  // Load app-level env vars to node-level env vars.
  process.env = { ...process.env, ...loadEnv(mode, process.cwd()) };

  return defineConfig({
    resolve: {
      alias: {
        $components: "/src/lib/components",
        $helpers: "/src/lib/helpers",
        $assets: "/src/lib/assets",
        $pages: "/src/lib/pages",
        $apis: "/src/lib/apis",
        $stores: "/src/lib/stores",
        $context: "/src/lib/context",
      },
    },
    plugins: [sentrySvelteKit({
      sourceMapsUploadOptions: {
        org: 'xxxxxxx',
        project: 'xxxxxxx',
      }
    }), sveltekit(), string({ include: "**/*.glsl" })],
  });
};

```

**Comment by eltigerchino** [comment]
> Hey @eltigerchino, I looked into our setup and I don't see any caching config on our side. My best guess would be that we're using the default caching setup provided by Vite/SvelteKit.
>
> Something to note, we've CloudFlare proxy siting infront of all the requests.

@SubhamPramanik could you check the response headers of `/_app/version.json` in your production environment? I'm wondering if it's possible that it's getting cached somehow. I'm likely wrong about this but anything's worth a shot at this point. Maybe we need to explicitly add a `no-cache` header or the like for `version.json`?

https://github.com/sveltejs/kit/blob/ce4fd764e271b1a461979dfaf9698af6f36e3714/packages/adapter-node/src/handler.js#L39-L42

**Comment by SubhamPramanik** [comment]
@eltigerchino Surprisingly enough I don't see a call to `/_app/version.json` in the network logs in the browser. 

But here is the response header for general `/_app/immutable/*` calls.

![Screenshot 2023-11-06 at 6 00 26 PM](https://github.com/sveltejs/kit/assets/22225798/4c3b5568-a8aa-459f-ad9c-68ec1968aa6d)

Our app is open to the public: https://chat.collectivai.com, incase you want to try things out.

**Comment by YankeeTube** [comment]
![image](https://github.com/sveltejs/kit/assets/34546950/ee995255-e7f5-4ab8-88fa-42349b37f528)
![image](https://github.com/sveltejs/kit/assets/34546950/d21d2f75-40cc-4545-b57c-c345a231987b)

lol

**Comment by quadroloop** [comment]
To anyone that still has this issue, tried everything in this thread but nothing works, I just want to share a solution that might help:

**Solution that worked for me:**
Clearing the Cached images and files in Chrome settings:
Goto: chrome://settings/clearBrowserData?search=clear
![image](https://github.com/sveltejs/kit/assets/29462205/5a37cf19-bed3-45d6-aca6-8a0688d929d0)

> I only left the images and files option checked because i don't want to delete all browsing data in that chrome profile.
After clearing the cache the site works as normal. 

**My case:**
- OS: Mac OS ventura
- Sveltekit: 1.27.6
- Hosted on Vercel


**Other notes:**
This error just came out of nowhere for me, I deploy changes to a branch Vercel deployment is fine and the error just appeared, and only on one chrome browser, testing on other browser my site works fine, it even works on incognito. But the errors persist on the regular chrome profile

Hope this helps, Cheers!

**Comment by YankeeTube** [comment]
> To anyone that still has this issue, tried everything in this thread but nothing works, I just want to share a solution that might help:
> 
> **Solution that worked for me:** Clearing the Cached images and files in Chrome settings: Goto: chrome://settings/clearBrowserData?search=clear ![image](https://private-user-images.githubusercontent.com/29462205/300188232-5a37cf19-bed3-45d6-aca6-8a0688d929d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzE4OTgsIm5iZiI6MTcwNjQzMTU5OCwicGF0aCI6Ii8yOTQ2MjIwNS8zMDAxODgyMzItNWEzN2NmMTktYmVkMy00NWQ2LWFjYTYtOGEwNjg4ZDkyOWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA4NDYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZmVkYmU4YjMzMmRlNTdjZWNkYjk0YmFiN2EzMTdjYTc4MzU5MDQxNmE1ZWFiYTcwZjQ1YTk4MWY3MDc1MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y2AOK2ogJ9FXUKRbwJGkXD0ayL5r5nrLUp7X8iidww4)
> 
> > I only left the images and files option checked because i don't want to delete all browsing data in that chrome profile.
> > After clearing the cache the site works as normal.
> 
> **My case:**
> 
> * OS: Mac OS ventura
> * Sveltekit: 1.27.6
> * Hosted on Vercel
> 
> **Other notes:** This error just came out of nowhere for me, I deploy changes to a branch Vercel deployment is fine and the error just appeared, and only on one chrome browser, testing on other browser my site works fine, it even works on incognito. But the errors persist on the regular chrome profile
> 
> Hope this helps, Cheers!

It may be useful in developing situations, but this error appears in users after production.
Therefore, it is not very helpful.

**Comment by eunukasiko** [comment]
Ditto, it only appears in deployment for us too (with adapter-node).

**Comment by LeeYoungHu** [comment]
This issue occur building files name change.
so, i fixed does not change file name with hash.
![image](https://github.com/sveltejs/kit/assets/65886694/6f862573-dae8-4ff1-8ea2-3fc396d0522c)
In this file line 638~640, building file name with hash
so i remove hash. 
and not occur this issue.
node_modules modify with 'patch-package'.

**Comment by elucidsoft** [comment]
I have this problem as well, it's really bad actually.  Here are some interesting observations. I am using Cloudflare Pages, and I noticed if you disable proxying entirely (meaning no cache of any kind is being applied by a cdn, it all seems to work).  Add proxy back (everything gets cached by cdn) it all breaks again. Even if I clear the CDN cache, it's still broken. Adding the version check stuff did not resolve the issue at all.  Going to the root of the app always works. If you load the initial page from root, everything works, every single time even with CDN cache on.  If you go to a non-root page, it's a gamble if it will work or not. Some work, some don't and it appears to be completely random.  Sometimes its trying to pull js files that simply don't exist in the deployment and were from previous deployments. Where is getting the reference to these? I have no idea as I am using an Incognito Window and I have cleared the CDN cache. So it really shouldn't have a reference to these old paths, but somehow it does.  It's possible some kind of caching header is really screwing things up somewhere as CDN's use edge caches as well and it's possible it's cached somewhere else along the route even if cleared? It's very odd. It's not just js files though, it's also css files.  Pretty much anything inside of immutable gets completely botched with a CDN enabled.

I was originally thinking it was related to Cloudflare Pages or the Adapter but since it works 100% fine if you disable the CDN I am not so sure. I have not tried uploading to another hosting provider, but based on what I saw in here it doesn't look like it would help.

**Comment by elucidsoft** [comment]
Would like to add a new discovery to this, if you enabled Signed Exchanges in Cloudflare and your clicking on the links in Google Search Results to test this behavior as I was since that's where the majority of complaints were coming from, those links are not pointing to your site. They are pointing to a Cached version of your page on Google Exchange and this completely breaks SvelteKit for some reason, so you cannot use this feature with SvelteKit.  You will need to disable this and then wait several days, weeks maybe for Google to drop your site from the Google Exchange network.

**Comment by LeeYoungHu** [comment]
Hi guys. 
I found a way fully handle this.
first, you see this my reply

[First way](https://github.com/sveltejs/kit/issues/9089#issuecomment-1943060440)

In addition, i remove immutable cash line by using patch-package.
So, not occur this situation.
But, sveltekit developer tell me, this way is page loading speed down.
So, you guys remind this.

**Comment by frederichoule** [comment]
This is causing a lot of issues on my end on each new version deploy. Setting the poll interval lower would probably help, but that means an extra few million monthly hits to handle (and to pay for, considering Cloudflare Pages pricing for example). I'm trying a lot of hacky things, but nothing works flawlessly yet.

**Comment by based64-eth** [comment]
I'm confused why this is still an issue, and why it is not fixed at the vite or sveltekit layer.

It seems like maaaany more people should be encountering this issue.

**Comment by frederichoule** [comment]
I was able to mostly fix the issue on my side. I'm using CloudFlare Pages, and whenever I deploy a new version I just purge the cache for the entire domain using the CloudFlare API. Doing this fix the issue for all new users arriving on the app, and then the ´pollInterval' takes care of the users already on the app.

**Comment by michaelchen01** [comment]
I'm also experiencing something similar. I'm deployed on Vercel using the vercel adapter. The initial SSR'd HTML loads correctly, but when we try to fetch the JS chunks, the browser decides to try to fetch them from the disk cache instead of loading fresh chunks, which causes unexpected behavior.

I've tried:
- setting a deterministic version name in svelte.config.js
- followed these instructions to track updates https://kit.svelte.dev/docs/configuration#version

I've noticed that version.json isn't even called as network event sometimes - I wonder if that's b/c the JS needed to do so isn't loaded properly?

Thanks!

**Comment by eugenechantk** [comment]
I am still experiencing the same problem after I:
1. set the `version.pollInterval` to 6000
2. set the version name as my commit hash

But some people still have the not found error. Anyone figured out a reliable solution?

**Comment by frederichoule** [comment]
If you clear your app's cache on each deploy, it works flawlessly. For example, on CloudFlare, use Caching -> Configuration -> Purge everything (or Custom purge).

**Comment by vecter** [comment]
> If you clear your app's cache on each deploy, it works flawlessly. For example, on CloudFlare, use Caching -> Configuration -> Purge everything (or Custom purge).

We're using Vercel without CloudFlare. Not sure if there's anything we can do with this setup to clear the app cache.

**Comment by DigitallyTailored** [comment]
Did you guys _just_ have this happen on a site too? I did as well for one also running through cloudflare as a dns and cache provider. Wondering if their cache maybe had a minute

**Comment by vecter** [comment]
> 
> I've noticed that version.json isn't even called as network event sometimes - I wonder if that's b/c the JS needed to do so isn't loaded properly?
> 

Yes, that may be the case. For example, in addition to a litany or 404s for a bunch of files, including

```
GET https://staging-app.usemantel.com/_app/immutable/entry/app.e6f98f24.js net::ERR_ABORTED 404 (Not Found)

...

TypeError: Failed to fetch dynamically imported module: https://staging-app.usemantel.com/_app/immutable/entry/start.3303bec4.js
```

The app's JS never loads. When I inspect the DOM, the only thing inside the body > div is the load script, which contains at the bottom:

```
Promise.all([
	import("./_app/immutable/entry/start.3303bec4.js"),
	import("./_app/immutable/entry/app.f7e92c3b.js")
]).then(([kit, app]) => {
	kit.start(app, element);
});
```

There is no further HTML loaded from the root layout, etc.  As you can see, the cached version is looking for `app.e6f98f24.js` but the newest version is `ap.f7e92c3b.js`.

**Comment by frederichoule** [comment]
@vecter - what does your `[x-vercel-cache](https://vercel.com/docs/edge-network/caching#x-vercel-cache)` header look like? By reading the docs, it seems that Vercel is suppose to clear the cache on every deploy.

**Comment by vecter** [comment]
@frederichoule 

![image](https://github.com/sveltejs/kit/assets/1099399/687226d8-c94b-4df3-a69c-6a72467eac13)

![image](https://github.com/sveltejs/kit/assets/1099399/81ff358c-d27e-4a68-acaf-b058a8f6aff6)

It says either HIT or MISS depending on whether or not it can find the file. Apologies for my noobie question but how does that relate to this issue?

I did a hard purge of the Vercel app's data cache but that didn't do anything.

**Comment by frederichoule** [comment]
I meant, the `x-vercel-cache` of your root page `staging-app.usemantel.com`. The main issue is that your `staging-app.usemantel.com` returns the HTML of an old build, so you have to find a way to invalidate the cache of that root URL.

**Comment by frederichoule** [comment]
Yeah it seems right - so your root page returns the correct scripts to be loaded, but those scripts don't load (example `scheduler.66c77ea2.js`). I can access that script from here without any problem. Can you check on your side what's the error?

![CleanShot 2024-07-08 at 09 01 45@2x](https://github.com/sveltejs/kit/assets/3178959/ccdd7649-a984-4c65-b725-e1595e52a496)

**Comment by vecter** [comment]
> Yeah it seems right - so your root page returns the correct scripts to be loaded, but those scripts don't load (example `scheduler.66c77ea2.js`). I can access that script from here without any problem. Can you check on your side what's the error?
> 
> ![CleanShot 2024-07-08 at 09 01 45@2x](https://private-user-images.githubusercontent.com/3178959/346634978-ccdd7649-a984-4c65-b725-e1595e52a496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTQ4NDYsIm5iZiI6MTcyMDQ1NDU0NiwicGF0aCI6Ii8zMTc4OTU5LzM0NjYzNDk3OC1jY2RkNzY0OS1hOTg0LTRjNjUtYjcyNS1lMTU5NWU1MmE0OTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMTYwMjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJkZjUwNWQ2YmQwM2ZhZTZlNzcxYjZlZTM3MmQ5ZWU2ZDlhODY2OGU0ZDQ5OTUwMmEyYzE2Y2E0OGIxYWJkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UM5dJ59fE0HKQ1JllTweODjbB-bUuXbQfLLEnRMogPk)

It must be a browser caching issue. I can load that URL (https://staging-app.usemantel.com/_app/immutable/chunks/scheduler.66c77ea2.js) fine in an Incognito chrome window. However, in my main Chrome window where I've been doing all of my development work, I get the 404. I'm pretty sure it's b/c Chrome is trying to load it form the disk cache:

![image](https://github.com/sveltejs/kit/assets/1099399/aa5eab7e-f248-4460-a570-8352b5c88658)

The Status Code shows "404 Not Found (from disk cache)". It assume itt's not in the cache because it's a new file from the most recent build. I don't know why Chrome doesn't try to fetch the file remotely. Maybe becauase the `Link:` value are all relative and not absolute?

**Comment by frederichoule** [comment]
Can you adjust the `Cache-control: public, immutable, max-age=31536000` header on Vercel? That means Chrome will cache the 404 pages for 365 days. It should be `no-store` instead. That's the root of your problem.

**Comment by vecter** [comment]
> Can you adjust the `Cache-control: public, immutable, max-age=31536000` header on Vercel? That means Chrome will cache the 404 pages for 365 days. It should be `no-store` instead. That's the root of your problem.

Thank you for that suggestion. I will look that up and try that now. Will let you know how it goes.

**Comment by vecter** [comment]
> Can you adjust the `Cache-control: public, immutable, max-age=31536000` header on Vercel? That means Chrome will cache the 404 pages for 365 days. It should be `no-store` instead. That's the root of your problem.

One thing: if I set it to `no-store`, wouldn't that mean that those pages are never cached? It seems that that would slow page loads significantly. Is there a better value like `no-cache` or something else?

**Comment by vecter** [comment]
> You should set `no-store` on 404 status code only, not all of them.
> 
> * 404 status: `no-store`
> * 200 status (root page): `public, must-revalidate, max-age=86400` (although you would have to invalidate the cache on each deploy, which Vercel does by default I think)
> * 200 status / immutable assets: `public, immutable, max-age=31536000`

That makes sense, thanks for spelling that out. I've scoured the Vercel docs on how to set the Cache-Control header conditioned on the response code status but I don't see how:

https://vercel.com/guides/how-to-configure-the-cache-control-response-header-in-vercel-projects#using-the-vercel.json-file
https://vercel.com/docs/edge-network/headers#cache-control-header

Am I totally missing something or is there a simple way to do it?

**Comment by frederichoule** [comment]
I haven't played with Vercel much, so I do not know exactly how to do it. I'll give it a try later today and see what I can find. In the meantime, I also found that: `https://vercel.com/docs/deployments/skew-protection`.

**Comment by vecter** [comment]
> I haven't played with Vercel much, so I do not know exactly how to do it. I'll give it a try later today and see what I can find. In the meantime, I also found that: https://vercel.com/docs/deployments/skew-protection.

Thanks for the reference, I'll try that and see if it resolves the issue somehow (hard to tell currently if it's exactly related)

**Comment by frederichoule** [comment]
If you find a way to `no-cache` your 404 urls, and clear the cache on the root page on every deploy, everything will work as intended!

**Comment by vecter** [comment]
> If you find a way to `no-store` your 404 urls, and clear the cache on the root page on every deploy, everything will work as intended!

Interesting, what do you mean by "clear the cache on the root page on every deploy"? I assume you mean the browser's cache of some files but I'm not quite sure.

**Comment by frederichoule** [comment]
> If you clear your app's cache on each deploy, it works flawlessly. For example, on CloudFlare, use Caching -> Configuration -> Purge everything (or Custom purge).

Like I said here, but I do not know how to do it on Vercel. I used to have the same bug you had when I deployed our app. Our error rate was skyrocketing on each deploy, but now it's 0% since we added a clear cache step on our deploy process.

**Comment by smart** [comment]
We're running into this issue too, Vercel is aggressively caching 404s. I'm not sure how the initial 404 is happening that causes the cache hit, I'm thinking it could be a race condition with one JS file calling another before the others are on disk? I've filed a ticket with Vercel, It's not clear to me how to no-store my 404s, but still looking into it on my own.

**Comment by smart** [comment]
I've confirmed that sveltekit is not returning the Cache-Control headers on a 404 when using (my preview server locally). Vercel is caching it, which is not what Sveltekit is asking it to do. 3 days with a ticket open to Vercel and not even a first reply.

**Comment by smart** [comment]
Hi all, created a PR with a solution that's working for me, there are probably better approaches, but this could be a good example of the problem. https://github.com/sveltejs/kit/pull/12526

**Comment by alexbjorlig** [comment]
I can reproduce this issue now, depoyed on Vercel (and even with skew protection enabled).

Repo is [here](https://github.com/21RISK/failed-css-preload).

To actually reproduce, check out [this video](https://vimeo.com/1019838983?share=copy) I recorded.

But essentially you have to:

1) Visit the deployed page
2) Add a code-change, bump the version and deploy
3) In **another tab** visit the site
4) Go back to the old tab and inspect how it's getting 404

**Comment by eltigerchino** [comment]
> I can reproduce this issue now, depoyed on Vercel (and even with skew protection enabled).
> 
> Repo is [here](https://github.com/21RISK/failed-css-preload).
> 
> To reproduce, check out [this video](https://vimeo.com/1019838983?share=copy) I recorded.
> 
> But essentially you have to:
> 
> 1. Visit the deployed page
> 2. Add a code-change, bump the version and deploy
> 3. In **another tab** visit the site
> 4. Go back to the old tab and inspect how it's getting 404



> I can reproduce this issue now, depoyed on Vercel (and even with skew protection enabled).
> 
> Repo is [here](https://github.com/21RISK/failed-css-preload).
> 
> To reproduce, check out [this video](https://vimeo.com/1019838983?share=copy) I recorded.
> 
> But essentially you have to:
> 
> 1. Visit the deployed page
> 2. Add a code-change, bump the version and deploy
> 3. In **another tab** visit the site
> 4. Go back to the old tab and inspect how it's getting 404

Hi Alex, thank you for the detailed video, it's really helpful. I don't currently have access to skew protection so I can't reproduce this but I'll forward the matter to @Rich-Harris @dummdidumm @trueadm who can look at it when they have some free time.

Like you said in the video, it's probably the new tab which is updating the cookie and causing the old tab to lose the correct cookie. I'd also recommend creating a new issue for this.

You may also be interested in this issue https://github.com/sveltejs/kit/issues/12592 which advocates for using a header instead of a cookie.

**Comment by museadam** [comment]
I had this same problem on some dynamic routes and I fixed it by adding a +page.ts file to the effected routes with this code in it:

`export const ssr = false;`

[https://kit.svelte.dev/docs/page-options#ssr](url)

**Comment by Rican7** [comment]
Hmm, I just ran into this after a deploy of a new version, but was only able to replicate it on mobile (Chrome 134, Android 15).

@dummdidumm I noticed your change in #12530 to use `cache-control: public, max-age=0, must-revalidate`, which I think makes sense, but unfortunately it seems that mobile browsers cache realllly hard (makes sense, considering the nature of mobile device usage).

**Does it not make sense to add a `no-store` value to the `cache-control` header?**

**Comment by dummdidumm** [comment]
Which adapter where you using, and did you have a chance to look at what the response cache headers were for the 404?

**Comment by Rican7** [comment]
> Which adapter where you using, and did you have a chance to look at what the response cache headers were for the 404?

Oh yea, that's really important information. I'm sorry that I left that out.

I'm using `@sveltejs/adapter-node` version 5.2.12.

And I wasn't able to look at the headers that my phone received, because phone, but I was able to look at the response via cURL to see the headers there:

```
 $ curl -i !!REDACTED!!
HTTP/2 404
date: Thu, 06 Mar 2025 09:47:48 GMT
content-length: 9
cache-control: public, max-age=0, must-revalidate
x-do-app-origin: !!REDACTED!!
x-do-orig-status: 404
vary: Accept-Encoding
cf-cache-status: BYPASS
set-cookie: !!REDACTED!!
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=R3f%2FRZS1Oy2lKf%2BrLbCtI3lHeTVdB7XZDwF5121Wzj3h3NM9iYtRg4UX%2FlhuWQWs8GXllpLo9Hh0%2BxqmwtqCWlcaQ%2FvBTVCaLBLzXbX8%2Bk%2FDazaBK0sw3zXPZujJPyyKhsl3iyeEG27%2FfoY%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 91c0ef0ddb487b06-DEN
alt-svc: h3=":443"; ma=86400
server-timing: cfL4;desc="?proto=TCP&rtt=7124&min_rtt=4874&rtt_var=2993&sent=8&recv=11&lost=0&retrans=0&sent_bytes=3373&recv_bytes=847&delivery_rate=750413&cwnd=65&unsent_bytes=0&cid=0e230936428921e2&ts=109&x=0"

Not found
```

**Comment by dann2g** [comment]
We've managed to temporarily fix in production with the following in `src/service-worker.ts`:
```
import { build, files, version } from '$service-worker';

self.addEventListener('fetch', (event: any) => {
  let url = new URL(event.request.url);

  if (url.origin === self.location.origin) {
    url.searchParams.set('ver', version);

    const modifiedRequest = new Request(url, {
      method: event.request.method,
      headers: event.request.headers,
      body: event.request.method === 'GET' ? null : event.request.body,
      mode: event.request.mode,
      credentials: event.request.credentials,
      cache: event.request.cache,
      redirect: event.request.redirect,
    });

    event.respondWith(fetch(modifiedRequest));
  }
});
```

**Comment by MathiasWP** [comment]
For people that are using Vercel and encountering this problem, here's a way to solve it:

```ts
// svelte.config.js
import vercel from '@sveltejs/adapter-vercel';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [vitePreprocess()],
	kit: {
		paths: {
			assets: `https://${process.env.VERCEL_URL}`
		},
		adapter: vercel()
	}
};

export default config;
```

Setting the `kit.paths.assets` to `https://${process.env.VERCEL_URL}` will make it so that every deployment points to the assets of its exact version, instead of the relative assets of the url. This will make your assets always available since Vercel has unlimited deployment retention.

**Comment by MathiasWP** [comment]
We have been using the `updated` approach for almost 2 years now, and we daily received `failed to load dynamic module` errors in our Sentry (we're talking thousands the last 90 days). This approach is the first one that has managed to eradicate these errors, but it doesn't feel like the perfect solution.

It's at least better than getting the errors, and we know that there are many cases where the users would have to perform a manual refresh because the page didn't load at all if they were unlucky on the timing. 

Just sharing my experience here. I kinda agree that this isn't a pretty solution which should be embraced by the Vercel adapter, but i just wanted to share it, because it does actually work.

**Comment by Rican7** [comment]
I use the `updated` approach for disabling CSR navigation, but it doesn't help the issue when a 404'd response for a CSS or JS file gets cached and won't revalidate.

I'm also not using Vercel, so that doesn't work around the issue for me.

Even then, I don't think that's the issue I'm running into. Maybe I should create a new issue? My issue is that 404 responses for assets that are being requested (due to just unfortunate timing, maybe?) [are cached and won't clear until a forced reload of that specific asset URL manually](https://github.com/sveltejs/kit/issues/9089#issuecomment-2703340012).

**Comment by amit13k** [comment]
So I ran into a similar situation where the browser was caching 404 responses between deployments and breaking things. I was using adapter-node with Cloudflare. The issue was that Cloudflare’s default caching configuration set the browser TTL to 4 hours; I just needed to change the browser TTL to “Respect Existing Headers” in the Cloudflare caching -> configuration settings. 

<img width="2165" height="351" alt="Image" src="https://github.com/user-attachments/assets/ed8de6fc-4f2a-418d-99d1-b44abac1f56a" />

**Comment by TorstenDittmann** [comment]
> > Hey @eltigerchino, I looked into our setup and I don't see any caching config on our side. My best guess would be that we're using the default caching setup provided by Vite/SvelteKit.
> > Something to note, we've CloudFlare proxy siting infront of all the requests.
> 
> [@SubhamPramanik](https://github.com/SubhamPramanik) could you check the response headers of `/_app/version.json` in your production environment? I'm wondering if it's possible that it's getting cached somehow. I'm likely wrong about this but anything's worth a shot at this point.
> 
> The node adapter currently sets cache headers for `/_app/immutable/*`. Maybe we should also explicitly add a `no-cache` header or the like for `version.json`?
> 
> [kit/packages/adapter-node/src/handler.js](https://github.com/sveltejs/kit/blob/ce4fd764e271b1a461979dfaf9698af6f36e3714/packages/adapter-node/src/handler.js#L39-L42)
> 
> Lines 39 to 42 in [ce4fd76](/sveltejs/kit/commit/ce4fd764e271b1a461979dfaf9698af6f36e3714)
>  // only apply to build directory, not e.g. version.json 
>  if (pathname.startsWith(`/${manifest.appPath}/immutable/`) && res.statusCode === 200) { 
>  	res.setHeader('cache-control', 'public,max-age=31536000,immutable'); 
>  }

100% this! When no cache header is set, the browser caches it by default. Similiar to issue happens with `/_app/env.js`.

**Comment by hyunbinseo** [comment]
> Error: TypeError: Failed to fetch dynamically imported module: `<path>`

It would be nice if client-side Sentry doesn't send the above error since [SvelteKit does try full page navigation](https://svelte.dev/docs/kit/adapter-vercel#Skew-protection).

Only if 1) dynamic JS failed to load and 2) there is no new version (matches the active client version) then an error can be thrown to notify that something is really wrong.

Or at least a better error message implying 404 could be sent.

e.g. Static module `<path>` not found. SvelteKit will force full-page navigation

I would love to use the `paths.assets` approach, but it doesn't work well with the Node.js adapter.
