### ISSUE TITLE
Issue when content rendered with `{@html ...}` contains a script tag

### ISSUE THREAD

**Issue by renevanpelt** [sveltejs/kit#9870]
### Describe the bug

When I retreive html from the backend using fetch, I can use the { @html '<foo>bar</foo>' } syntax. 

However, whenever that html markup contains, for example, an embeddable widget. Like an embedded tweet or instagram post, the rendering becomes unreliable. 

Basically, when I get the page directly from typing in the url in the browser, everything is rendered well. But when I navigate to such a page with an internal link, it doesn't. 

When trying to replicate this in this [REPL](https://www.sveltelab.dev/#code=N4IgdADgTgpgLnAljKUDGIBcoBmiA2MWoaA9gHZwyUDOxIA1ouQCZYg0BuM%2BV%2BAhgCMAtAFdEADn4gANCEGicOFFgDaARgBMAZhnqADDICcM7QBY96gOyWArHv3qZEi0ZtGJd0xduftmywA2Swt1awcnM1DDE3MvA3swwwNdA08DJwknMJsw7PVgjO8ZX1MAsML1UPCiqIdjYoqQ41z9RP10tstk-V1A3LCHEwMTN2LS-0aDS3yepzi66djq8qqHROmmiVb25IKHCziJgLMTM09zmUWYqfKOy1bUrqSvI78Ao3mV5qKmv%2BfHM0zBs7ukar11t0rhsNp1svd-l9jLprg04mFQQ8HE8NoYJE8nGMwq5hvoLIFOhtqvY3mVjEizME4kYUdE0dV8nCfmsEg45q8fO96XodHT0fo7u0uWEaYKxRYzCdKrCIg4wYVAQtDgF0YMMUFIXkoTLxkKtLpJrqPgNqariab5fF1NKEfsinFJloaeVNPYWfUvQ4ALoAXzDcgg-DQDH4AHMYGAAFY0Cj0PCEehkSjUOB0bCMZhsTAcbi8HhCMSSaRyBRKFSYDSipZTGKtUlI463bnwjWE4b7LX1ZaWaU89TtDazB2WhUXYKXRlXYeo4f6%2B28sKeIluzVyz1usetSJs1duzT5O4doXi-vwvatLmD5u6v396Igg0m2meps3YceLENwRfRDG-HVqkpT9NQ%2BMEdjVPlihXdkEN%2BZ1p3AkdDR3eY7n5TdEJPZC1x5QF8KA-Jh07XVIMROliOiTlDVI9RVxuQMkPFPC0IpO0tF4nouJiUl2nyWUSjNX8GmHQJbTI0jXV7BxlSudxWlbSxVkU%2B1gRaQCDyvR0jB8QxFwXec-AVQjpNktDfgUu19GUsxWjgpowOKIylyuYJbBRcyCKHIi%2BPXZjKg1ETmnc5ljO8kp538p8-y7EL8jCpj8gVD80kAiEN2mHSTTk%2BF1VVKLXBixdbHirzEqkqYVTskr3T3DDPNsSIfN0WwlSuCyrisqYaOw9CPJ8HrTli7rGjY30A1mgxQ3DDh0HoFhEFgNA4FIKAAE96H4CAIDAAALOAAFt8DTAgiHzLMqFoegmFYdguB4PgK3EKRZHkRRlCgNRAlAvpPCsEx%2BmcCwJBMCRDECWI7mqDVSU8QI7hkQGDig5G6Pubcej6JFUNA8k0bBnoGN0gxYdJhoMZGXjgjGSYjFJVwbXiUL0cJmodxOewquKSZnPRmmyaGBndP3dT6aKQJuZo5j%2B1WDKDQ9D5b2NYaXiaOWpmElCd3JO9eMglnVQKlimL2DVDm1FSRcC2IBga%2BSmvk1z9kXAwKaJEDTFaWmTNaH21IdzYbgxgCjSpkUcIQ7dGZsC2XeKqD4Q9%2BcspI1OjV9kzdkp-Yxl18UOUw1DbbDpK6b9vKzXHT9z3g2XCdr54G7XXHcibzszejzYtYH5S4lR-2nRdN306w6qo71Wum%2B0GwMeFmO66rwP7dn42tCcUfpmX4Osfgvf9EWkM5HwRBBFW9aYE27a9vzABhUhRGzKAwFessrozW6KHu3Mj1CwvVLO9EQn1qw-TrP9BsdMG59xIlnYIJ8GjZVQkydWMw9LWzpCXE4nhbCkkCtoHyZoAQ6hOEJLBORNYYIdngryC447mkdpTYCKsmhmBiIzDWNDtYDklK8XChd8a8TLnwjuCIF4IyYk8Q4ugjDzicIQ1hCD8gDBwZMBhtgbAqObIGcOqCJTYOMP2cK1DpiejJCIlC7D0YPkhH3fQScTLMMkqMUxFiNGqxOATOkE09EzXaOjIOXgEHvg0gaFB%2B8YiwU-PpKE%2B4pylCcabUkS9si-jZsaNuXJwZoK6E47u9gUFgwcbyIpDlQI%2BgUbwnmOCDEzVqV42huDd7tP8fDdGFodRmKYu2UwXSqJ9KAgMr8wx5qw1CbPAYaV%2B7U2DGGJZcgoCvyoHmUAa0NpbV2vQAA1JGeMn8UDcA-smH%2BN0SD-xzBsgsz1ixfzAZWL6NZfr1g0KRTQexlbcjoWozWGw6FoMGHnNpdJtyJCbi8M2QtXFgtHj%2BJ4qDs7xPZi8RFrDoVtlVMM9GicOavjpC4BySt4IJ1KkQiZ-MiGBkCWfOQBy4wJkeZckA6ZWV3RuUA%2B5JY3rlnAVWb6tY-oAz2ISkKSD17Y3QTjRG4tspaLjiPWJzcQXpMsKkHmqVSqYOyhCrwJcRmWzynM5imV4ljM5toMGAQ4EULJd4lIXNBn8RdVYnoVJnXWtVZUQ4NrnAEh1VBCmVjeH6DGUPXBE5IoBG2FhURViwR9kLlpP2zMbD7jDaMbxdRM2YyNHm-VoasIwnjdiHGPz7RWMEUVHG0soUNysbiOtrrCrQWMHEtt0QtyOr9ouSOYISYhI7c0UeUNeKArEfHbucdfaaSnfw-IU5c22ujVW2NHsE2rAjSG3Vepw73k8f8ZtTr010Q7sa%2BSF5z3wntf8Xd%2BaASdHSNItO3Jsl5WqZYVmrr9w2ztK%2BwqwV92muNpMKw5iCmm28ZoTQhRNDpF8kIzx247bkr-Y%2B5hzEBI3ocPapmwi8pyv3GXUFTbEnzu9kGqwGcDQEZkDR6edGM0wT0u0btNiY79pVfaUeA7R0BE0FwvQejLjjjjpHFj%2BaUUGFtfMH9fwDyrH5hcJOszYr-JXm3J4wRQYOBcuWmO47LjepPnKxTynxL2xXp7HhWCtOiIMLp9VBhHgIWMyjaZS97WSdlT8eScmXVUcU5USzpRhY2ZnhrYWPEwijB7QxiwVgAgQecPYRj6L-Wd0JV7A8%2BsQtTsXP8%2BmMWwTxd0lYJLKXggSHS94g%2Buk%2BOhP1AizopJpaSJ8F0iQ5iEGVA4YUqTMNqHAXFe24TMlnC9aNQNv0NhhvR1G0ewEZgJPqSsdUCmsmvUKYPKFrw4W1MWqY7RbSdnFtnHm9N%2BJs3dILbnmk82ztmOoq8BFkwtgfBdQCJ9uKJQk4EP5ro-mP3-K-dsPzZRhgBaBE1Vt4xRhS32jNrrRT-ZPUwt0X0EZxi4sutHoxokr7fsrpKCZAh0Pd5efodM59WDKlhE1QMbVssfNiqPYgyJblrTxAbVQ-cGOwbyek3M4DKnrMDExOS7b-dohnFF-lvbhXztz0u9%2Bq2hnOYmi9o5V4XSnEfrHBFHWwuJEaj5n90ztrQlqyuD0%2BqHOInEWQRhQJw6bPis5879emxRSTeCzubGG2j5oN9PSkAsZ8CkEEPwfAYA0A0FueyzM1yHr5iekWXlZYBACpeVAkVDZSjrn3dqjFzYdLJ309CEdYxKkFWsZ2Ww5OShdcChXpHzjq8AVr%2BqnS7Vq8B6lFZyYbuzj2Er65rvCW6-j4%2B2Q2S9xhMLjtiZpOK%2BzgXD8EnZRlLq8T87zpbv7he-82h-PjmFxm%2Bk9X-1TpvV7%2BLyuDvtv4%2BO9Jz9NPk-JRlHn7bZfsn9%2BJOds4OOoa%2BdIOilu2%2BJQu%2B7eHM7%2BNex%2BVefeP2v%2Bki-%2BTegBlk4BP2oBt%2BI%2Bui8wUBo%2Be%2Bb%2BU%2BukM%2BJQXUqBQ%2BwmGBlwQB4Bzej%2BpOAsN%2Bq20BL%2BA%2Bki8Bp2XyBoFec%2Bfmf%2BVwV%2BK%2BW%2BeBJwH2hBT%2BHB5er%2BcBXBWkfBnCp%2Bw%2BMiwhS%2BFwYhY8LB0ONIRBMB8hbaPBWsyhnskOah0mNB0O0O%2BCEhkB9hU0U0zBz%2BchXB7QJh-6dkAyAhlhg%2B8ES%2BH2rId%2BC44hLBXUFoBhnB%2B%2BnhmG8qK2qhnY-h2UtBth9%2BLBTIYBI%2BOBOhrhNwsBxhihcRMsCR3%2Bfh1iGhNhgBJw6%2B6RYRwBPg0h7BxBBR3BA%2BuO%2B6OCuKemtaxePOQGNIZwK%2Bc2XOwUdiE%2BDak63h9hgQGoQ0PQNghOiB%2BIscToqaJgVgewU4nCds3qKxdkmq8IcctWDGFoQxRKPyW8N29hPRyhUKuU2G9hJxMyrSNCSEZSnGRcaKrsARuxGxHqzQ9GKxeMeu9hpmg6I2BckwwJjqja5xloGxl4qqo4129GVgo4R4LqpOJoIJ2uHet222LRRhbR9elaka9edSWxlh3qmxWE2S4GzOmswu2J4aFiVJQGPOTieRIowSSwSaKEgG7iCBy2bmxe6iOS%2BcHOOc%2B6LUmEqGIhJBChh%2Bn%2BSBFhzRu%2BxWroKsSRaE8pS%2BxJHhRRvwZhmcjC3JpI2a-mOIUInYZkJQ-Mga9MxBMunR-B7Q-RrJQEL6P%2B56CW2kkpMR7RZJOC6pjsiBXJrSh%2BYa-J9oOpfpaw%2Bp7hqpwaJK5ss%2BMhbujS9Q-unp8kAJ9Gwm9EDkSJxe8hmpMZCZpaBuqZRQSRfs8pk%2B7BZeNwReY4S6PiIoSKHirRhpyp5BX%2BAS1BARoh-i9RIRYR5pDQPZyZR%2BIp1eGBdZC%2B-%2By%2Bo5OhtRAsLhshSU05jZH%2B-ZyZ-ei5F%2BCpK5QsY5QsH2uBoZzYY%2BSZu5wpFBThQ5KRI5Z5a5jBABm5xBt5gZfZPeB5VBQhaBJ5Whq5zBwBdhX5GpiphRFsShIZ6ZR5lR6R2h4F4BAOuRW5dUO5B%2BUxnyCFABSFwFmh9hbBwBCUURN5MFJJeFmSBFh5z5i%2Br5kFWRP2X2mFzpkyjsMZ88biXZUk0ZFi5qOJCm8kAydZHW0Quiu%2BWZN5UmLCVF5ZQlfhup7MiZv5eF8OPhapk5slf4uiYIQ0a6WsaaNSqiglsu5RS5CpC5Pg4%2BtRoR75I%2BDpHFMlXFjSZ8Sy58WeVA8eFAeAsYSYSe10Ke2YaeoAGeICfKOezykCwq7yoyoxHCAibCHWlGZqFa3Y4sCJ6MNkE8b6Tmb2qk06oxWklZhc6mBaH2NKoSioVwPm5mDaSJzZ7QpKllnCoEYMeVDkk8SkRVVeJqWJHU9ibJeGsiPJ-iJwAcxWA8k6zMlJY1QE9uDCClbEneg1SRQpauwsZ6Mc246VKsh%2BAwlVgwSSOS3p56GwkuSVvyyGQG8IAyVi2xtk7c4i4cEaDSDc2JkiRxQFouYWqm9sk%2Bg1uWKcPq5sGoXEgNq8aq-VoK%2B1BV5V24J1WGZJaG8lS2QG1UVFEWUmVgTwd6Da4p66raL1nq8y8Rz1QK7c3oTJHZQG11xEyVqaX6llP47ZNCAuEs-wLorNrpZ6XNncyaQEgiMKJZA8Q0b1PQH1-BdsQGiu521iZ1Zu56Xh7a8NjNg8CoGo2FR20Jjp7aAe-1B2gNWmtGoN5cPxtEOuUNQNtcsN2uxVe1mtZVto1aylxa7Vht7cPQaN4s0u7cU4Z6VxKtu19ZLtC6X1OtHiGtpVU6vcocCNp2CZcK%2Bi7ls0mZeEZhft3Otit6FV4N81o1MuAIXUpI4enAiAvlWYAVQVFyoVACtykVDyoC-KsVQqbyMCHyrVN1xeQKoogtL10pqatGP4tNLp4irJOV-uF6%2BVp2uujtA17c84AwQ0ik3qmdPdTNt1GK7qxZZassjJ2suOpddEs07tYp2VvSlttFLqmdAG3yyludq8AWBdwK1NeEJ9J6gI%2BSrpJd7QKIyQQpncnaDxJ6Dcvcokltw9Dk5tcK-ovu4%2BeRnlQAA) I run into another few problems:

1. It doesn't work on the first request now
2. When I try to get the `"</script>"` string into a variable, the compiler complains (see image).

![image](https://user-images.githubusercontent.com/6897635/236880725-b88875a7-72a2-49f4-b215-98d690c4ac86.png)

Am I doing something wrong? Can't find any documentation on the subject.

Thanks.

### Reproduction

[REPL](https://www.sveltelab.dev/#code=N4IgdADgTgpgLnAljKUDGIBcoBmiA2MWoaA9gHZwyUDOxIA1ouQCZYg0BuM%2BV%2BAhgCMAtAFdEADn4gANCEGicOFFgDaARgBMAZhnqADDICcM7QBY96gOyWArHv3qZEi0ZtGJd0xduftmywA2Swt1awcnM1DDE3MvA3swwwNdA08DJwknMJsw7PVgjO8ZX1MAsML1UPCiqIdjYoqQ41z9RP10tstk-V1A3LCHEwMTN2LS-0aDS3yepzi66djq8qqHROmmiVb25IKHCziJgLMTM09zmUWYqfKOy1bUrqSvI78Ao3mV5qKmv%2BfHM0zBs7ukar11t0rhsNp1svd-l9jLprg04mFQQ8HE8NoYJE8nGMwq5hvoLIFOhtqvY3mVjEizME4kYUdE0dV8nCfmsEg45q8fO96XodHT0fo7u0uWEaYKxRYzCdKrCIg4wYVAQtDgF0YMMUFIXkoTLxkKtLpJrqPgNqariab5fF1NKEfsinFJloaeVNPYWfUvQ4ALoAXzDcgg-DQDH4AHMYGAAFY0Cj0PCEehkSjUOB0bCMZhsTAcbi8HhCMSSaRyBRKFSYDSipZTGKtUlI463bnwjWE4b7LX1ZaWaU89TtDazB2WhUXYKXRlXYeo4f6%2B28sKeIluzVyz1usetSJs1duzT5O4doXi-vwvatLmD5u6v396Igg0m2meps3YceLENwRfRDG-HVqkpT9NQ%2BMEdjVPlihXdkEN%2BZ1p3AkdDR3eY7n5TdEJPZC1x5QF8KA-Jh07XVIMROliOiTlDVI9RVxuQMkPFPC0IpO0tF4nouJiUl2nyWUSjNX8GmHQJbTI0jXV7BxlSudxWlbSxVkU%2B1gRaQCDyvR0jB8QxFwXec-AVQjpNktDfgUu19GUsxWjgpowOKIylyuYJbBRcyCKHIi%2BPXZjKg1ETmnc5ljO8kp538p8-y7EL8jCpj8gVD80kAiEN2mHSTTk%2BF1VVKLXBixdbHirzEqkqYVTskr3T3DDPNsSIfN0WwlSuCyrisqYaOw9CPJ8HrTli7rGjY30A1mgxQ3DDh0HoFhEFgNA4FIKAAE96H4CAIDAAALOAAFt8DTAgiHzLMqFoegmFYdguB4PgK3EKRZHkRRlCgNRAlAvpPCsEx%2BmcCwJBMCRDECWI7mqDVSU8QI7hkQGDig5G6Pubcej6JFUNA8k0bBnoGN0gxYdJhoMZGXjgjGSYjFJVwbXiUL0cJmodxOewquKSZnPRmmyaGBndP3dT6aKQJuZo5j%2B1WDKDQ9D5b2NYaXiaOWpmElCd3JO9eMglnVQKlimL2DVDm1FSRcC2IBga%2BSmvk1z9kXAwKaJEDTFaWmTNaH21IdzYbgxgCjSpkUcIQ7dGZsC2XeKqD4Q9%2BcspI1OjV9kzdkp-Yxl18UOUw1DbbDpK6b9vKzXHT9z3g2XCdr54G7XXHcibzszejzYtYH5S4lR-2nRdN306w6qo71Wum%2B0GwMeFmO66rwP7dn42tCcUfpmX4Osfgvf9EWkM5HwRBBFW9aYE27a9vzABhUhRGzKAwFessrozW6KHu3Mj1CwvVLO9EQn1qw-TrP9BsdMG59xIlnYIJ8GjZVQkydWMw9LWzpCXE4nhbCkkCtoHyZoAQ6hOEJLBORNYYIdngryC447mkdpTYCKsmhmBiIzDWNDtYDklK8XChd8a8TLnwjuCIF4IyYk8Q4ugjDzicIQ1hCD8gDBwZMBhtgbAqObIGcOqCJTYOMP2cK1DpiejJCIlC7D0YPkhH3fQScTLMMkqMUxFiNGqxOATOkE09EzXaOjIOXgEHvg0gaFB%2B8YiwU-PpKE%2B4pylCcabUkS9si-jZsaNuXJwZoK6E47u9gUFgwcbyIpDlQI%2BgUbwnmOCDEzVqV42huDd7tP8fDdGFodRmKYu2UwXSqJ9KAgMr8wx5qw1CbPAYaV%2B7U2DGGJZcgoCvyoHmUAa0NpbV2vQAA1JGeMn8UDcA-smH%2BN0SD-xzBsgsz1ixfzAZWL6NZfr1g0KRTQexlbcjoWozWGw6FoMGHnNpdJtyJCbi8M2QtXFgtHj%2BJ4qDs7xPZi8RFrDoVtlVMM9GicOavjpC4BySt4IJ1KkQiZ-MiGBkCWfOQBy4wJkeZckA6ZWV3RuUA%2B5JY3rlnAVWb6tY-oAz2ISkKSD17Y3QTjRG4tspaLjiPWJzcQXpMsKkHmqVSqYOyhCrwJcRmWzynM5imV4ljM5toMGAQ4EULJd4lIXNBn8RdVYnoVJnXWtVZUQ4NrnAEh1VBCmVjeH6DGUPXBE5IoBG2FhURViwR9kLlpP2zMbD7jDaMbxdRM2YyNHm-VoasIwnjdiHGPz7RWMEUVHG0soUNysbiOtrrCrQWMHEtt0QtyOr9ouSOYISYhI7c0UeUNeKArEfHbucdfaaSnfw-IU5c22ujVW2NHsE2rAjSG3Vepw73k8f8ZtTr010Q7sa%2BSF5z3wntf8Xd%2BaASdHSNItO3Jsl5WqZYVmrr9w2ztK%2BwqwV92muNpMKw5iCmm28ZoTQhRNDpF8kIzx247bkr-Y%2B5hzEBI3ocPapmwi8pyv3GXUFTbEnzu9kGqwGcDQEZkDR6edGM0wT0u0btNiY79pVfaUeA7R0BE0FwvQejLjjjjpHFj%2BaUUGFtfMH9fwDyrH5hcJOszYr-JXm3J4wRQYOBcuWmO47LjepPnKxTynxL2xXp7HhWCtOiIMLp9VBhHgIWMyjaZS97WSdlT8eScmXVUcU5USzpRhY2ZnhrYWPEwijB7QxiwVgAgQecPYRj6L-Wd0JV7A8%2BsQtTsXP8%2BmMWwTxd0lYJLKXggSHS94g%2Buk%2BOhP1AizopJpaSJ8F0iQ5iEGVA4YUqTMNqHAXFe24TMlnC9aNQNv0NhhvR1G0ewEZgJPqSsdUCmsmvUKYPKFrw4W1MWqY7RbSdnFtnHm9N%2BJs3dILbnmk82ztmOoq8BFkwtgfBdQCJ9uKJQk4EP5ro-mP3-K-dsPzZRhgBaBE1Vt4xRhS32jNrrRT-ZPUwt0X0EZxi4sutHoxokr7fsrpKCZAh0Pd5efodM59WDKlhE1QMbVssfNiqPYgyJblrTxAbVQ-cGOwbyek3M4DKnrMDExOS7b-dohnFF-lvbhXztz0u9%2Bq2hnOYmi9o5V4XSnEfrHBFHWwuJEaj5n90ztrQlqyuD0%2BqHOInEWQRhQJw6bPis5879emxRSTeCzubGG2j5oN9PSkAsZ8CkEEPwfAYA0A0FueyzM1yHr5iekWXlZYBACpeVAkVDZSjrn3dqjFzYdLJ309CEdYxKkFWsZ2Ww5OShdcChXpHzjq8AVr%2BqnS7Vq8B6lFZyYbuzj2Er65rvCW6-j4%2B2Q2S9xhMLjtiZpOK%2BzgXD8EnZRlLq8T87zpbv7he-82h-PjmFxm%2Bk9X-1TpvV7%2BLyuDvtv4%2BO9Jz9NPk-JRlHn7bZfsn9%2BJOds4OOoa%2BdIOilu2%2BJQu%2B7eHM7%2BNex%2BVefeP2v%2Bki-%2BTegBlk4BP2oBt%2BI%2Bui8wUBo%2Be%2Bb%2BU%2BukM%2BJQXUqBQ%2BwmGBlwQB4Bzej%2BpOAsN%2Bq20BL%2BA%2Bki8Bp2XyBoFec%2Bfmf%2BVwV%2BK%2BW%2BeBJwH2hBT%2BHB5er%2BcBXBWkfBnCp%2Bw%2BMiwhS%2BFwYhY8LB0ONIRBMB8hbaPBWsyhnskOah0mNB0O0O%2BCEhkB9hU0U0zBz%2BchXB7QJh-6dkAyAhlhg%2B8ES%2BH2rId%2BC44hLBXUFoBhnB%2B%2BnhmG8qK2qhnY-h2UtBth9%2BLBTIYBI%2BOBOhrhNwsBxhihcRMsCR3%2Bfh1iGhNhgBJw6%2B6RYRwBPg0h7BxBBR3BA%2BuO%2B6OCuKemtaxePOQGNIZwK%2Bc2XOwUdiE%2BDak63h9hgQGoQ0PQNghOiB%2BIscToqaJgVgewU4nCds3qKxdkmq8IcctWDGFoQxRKPyW8N29hPRyhUKuU2G9hJxMyrSNCSEZSnGRcaKrsARuxGxHqzQ9GKxeMeu9hpmg6I2BckwwJjqja5xloGxl4qqo4129GVgo4R4LqpOJoIJ2uHet222LRRhbR9elaka9edSWxlh3qmxWE2S4GzOmswu2J4aFiVJQGPOTieRIowSSwSaKEgG7iCBy2bmxe6iOS%2BcHOOc%2B6LUmEqGIhJBChh%2Bn%2BSBFhzRu%2BxWroKsSRaE8pS%2BxJHhRRvwZhmcjC3JpI2a-mOIUInYZkJQ-Mga9MxBMunR-B7Q-RrJQEL6P%2B56CW2kkpMR7RZJOC6pjsiBXJrSh%2BYa-J9oOpfpaw%2Bp7hqpwaJK5ss%2BMhbujS9Q-unp8kAJ9Gwm9EDkSJxe8hmpMZCZpaBuqZRQSRfs8pk%2B7BZeNwReY4S6PiIoSKHirRhpyp5BX%2BAS1BARoh-i9RIRYR5pDQPZyZR%2BIp1eGBdZC%2B-%2By%2Bo5OhtRAsLhshSU05jZH%2B-ZyZ-ei5F%2BCpK5QsY5QsH2uBoZzYY%2BSZu5wpFBThQ5KRI5Z5a5jBABm5xBt5gZfZPeB5VBQhaBJ5Whq5zBwBdhX5GpiphRFsShIZ6ZR5lR6R2h4F4BAOuRW5dUO5B%2BUxnyCFABSFwFmh9hbBwBCUURN5MFJJeFmSBFh5z5i%2Br5kFWRP2X2mFzpkyjsMZ88biXZUk0ZFi5qOJCm8kAydZHW0Quiu%2BWZN5UmLCVF5ZQlfhup7MiZv5eF8OPhapk5slf4uiYIQ0a6WsaaNSqiglsu5RS5CpC5Pg4%2BtRoR75I%2BDpHFMlXFjSZ8Sy58WeVA8eFAeAsYSYSe10Ke2YaeoAGeICfKOezykCwq7yoyoxHCAibCHWlGZqFa3Y4sCJ6MNkE8b6Tmb2qk06oxWklZhc6mBaH2NKoSioVwPm5mDaSJzZ7QpKllnCoEYMeVDkk8SkRVVeJqWJHU9ibJeGsiPJ-iJwAcxWA8k6zMlJY1QE9uDCClbEneg1SRQpauwsZ6Mc246VKsh%2BAwlVgwSSOS3p56GwkuSVvyyGQG8IAyVi2xtk7c4i4cEaDSDc2JkiRxQFouYWqm9sk%2Bg1uWKcPq5sGoXEgNq8aq-VoK%2B1BV5V24J1WGZJaG8lS2QG1UVFEWUmVgTwd6Da4p66raL1nq8y8Rz1QK7c3oTJHZQG11xEyVqaX6llP47ZNCAuEs-wLorNrpZ6XNncyaQEgiMKJZA8Q0b1PQH1-BdsQGiu521iZ1Zu56Xh7a8NjNg8CoGo2FR20Jjp7aAe-1B2gNWmtGoN5cPxtEOuUNQNtcsN2uxVe1mtZVto1aylxa7Vht7cPQaN4s0u7cU4Z6VxKtu19ZLtC6X1OtHiGtpVU6vcocCNp2CZcK%2Bi7ls0mZeEZhft3Otit6FV4N81o1MuAIXUpI4enAiAvlWYAVQVFyoVACtykVDyoC-KsVQqbyMCHyrVN1xeQKoogtL10pqatGP4tNLp4irJOV-uF6%2BVp2uujtA17c84AwQ0ik3qmdPdTNt1GK7qxZZassjJ2suOpddEs07tYp2VvSlttFLqmdAG3yyludq8AWBdwK1NeEJ9J6gI%2BSrpJd7QKIyQQpncnaDxJ6Dcvcokltw9Dk5tcK-ovu4%2BeRnlQAA)

### System Info

```Shell
See the REPL, I guess?
```

### Severity

blocking an upgrade

**Comment by fiorelorenzo** [comment]
I don't think any of your issues are SvelteKit issues:

1. looks like a CORS problem;
2. is fixed by escaping the `/ ` with a `\`, like this: ` ...  <\/script>";`.

**Comment by Rich-Harris** [comment]
Yeah the `</script>` thing is expected. That sequence of characters in HTML will always close any currently open `<script>` element, even if it's inside a string or a comment, and Svelte inherits that behaviour. It looks like the REPL has since been updated and I'm not seeing the error overlay, is there still an issue here?

**Comment by renevanpelt** [comment]
> Yeah the `</script>` thing is expected. That sequence of characters in HTML will always close any currently open `<script>` element, even if it's inside a string or a comment, and Svelte inherits that behaviour. It looks like the REPL has since been updated and I'm not seeing the error overlay, is there still an issue here?

Thanks, I understand the `</script>` thing now. In the REPL, I've done a little trick so that the string is split up and doesn't contain `</script>`

[I have updated a REPL to show my situation.](https://www.sveltelab.dev/#code=N4IgdADgTgpgLnAljKUDGIBcoBmiA2MWoaA9gHZwyUDOxIA1ouQCZYg0BuM%2BV%2BAhgCMAtAFdEADn4gANCEGicOFFgDaARgBMAZhnqADDICcM7QBY96gOyWArHv3qZEi0ZtGJd0xduftmywA2Swt1awcnM1DDE3MvA3swwwNdA08DJwknMJsw7PVgjO8ZX1MAsML1UPCiqIdjYoqQ41z9RP10tstk-V1A3LCHEwMTN2LS-0aDS3yepzi66djq8qqHROmmiVb25IKHCziJgLMTM09zmUWYqfKOy1bUrqSvI78Ao3mV5qKmv%2BfHM0zBs7ukar11t0rhsNp1svd-l9jLprg04mFQQ8HE8NoYJE8nGMwq5hvoLIFOhtqvY3mVjEizME4kYUdE0dV8nCfmsEg45q8fO96XodHT0fo7u0uWEaYKxRYzCdKrCIg4wYVAQtDgF0YMMUFIXkoTLxkKtLpJrqPgNqariab5fF1NKEfsinFJloaeVNPYWfUvQ4ALoAXzDcgg-DQDH4AHMYGAAFY0Cj0PCEehkSjUOB0bCMZhsTAcbi8HhCMSSaRyBRKFSYDSipZTGKtUlI463bnwjWE4b7LX1ZaWaU89TtDazB2WhUXYKXRlXYeo4f6%2B28sKeIluzVyz1usetSJs1duzT5O4doXi-vwvatLmD5u6v396Igg0m2meps3YceLENwRfRDG-HVqkpT9NQ%2BMEdjVPlihXdkEN%2BZ1p3AkdDR3eY7n5TdEJPZC1x5QF8KA-Jh07XVIMROliOiTlDVI9RVxuQMkPFPC0IpO0tF4nouJiUl2nyWUSjNX8GmHQJbTI0jXV7BxlSudxWlbSxVkU%2B1gRaQCDyvR0jB8QxFwXec-AVQjpNktDfgUu19GUsxWjgpowOKIylyuYJbBRcyCKHIi%2BPXZjKg1ETmnc5ljO8kp538p8-y7EL8jCpj8gVD80kAiEN2mHSTTk%2BF1VVKLXBixdbHirzEqkqYVTskr3T3DDPNsSIfN0WwlSuCyrisqYaOw9CPJ8HrTli7rGjY30A1mgxQ3DDh0HoFhEFgNA4FIKAAE96H4CAIDAAALOAAFt8DTAgiHzLMqFoegmFYdguB4PgK3EKRZHkRRlCgNRAlAvpPCsEx%2BmcCwJBMCRDECWI7mqDVSU8QI7hkQGDig5G6Pubcej6JFUNA8k0bBnoGN0gxYdJhoMZGXjgjGSYjFJVwbXiUL0cJmodxOewquKSZnPRmmyaGBndP3dT6aKQJuZo5j%2B1WDKDQ9D5b2NYaXiaOWpmElCd3JO9eMglnVQKlimL2DVDm1FSRcC2IBga%2BSmvk1z9kXAwKaJEDTFaWmTNaH21IdzYbgxgCjSpkUcIQ7dGZsC2XeKqD4Q9%2BcspI1OjV9kzdkp-Yxl18UOUw1DbbDpK6b9vKzXHT9z3g2XCdr54G7XXHcibzszejzYtYH5S4lR-2nRdN306w6qo71Wum%2B0GwMeFmO66rwP7dn42tCcUfpmX4Osfgvf9EWkM5HwRBBFW9aYE27a9vzABhUhRGzKAwFessrozW6KHu3Mj1CwvVLO9EQn1qw-TrP9BsdMG59xIlnYIJ8GjZVQkydWMw9LWzpCXE4nhbCkkCtoHyZoAQ6hOEJLBORNYYIdngryC447mkdpTYCKsmhmBiIzDWNDtYDklK8XChd8a8TLnwjuCIF4IyYk8Q4ugjDzicIQ1hCD8gDBwZMBhtgbAqObIGcOqCJTYOMP2cK1DpiejJCIlC7D0YPkhH3fQScTLMMkqMUxFiNGqxOATOkE09EzXaOjIOXgEHvg0gaFB%2B8YiwU-PpKE%2B4pylCcabUkS9si-jZsaNuXJwZoK6E47u9gUFgwcbyIpDlQI%2BgUbwnmOCDEzVqV42huDd7tP8fDdGFodRmKYu2UwXSqJ9KAgMr8wx5qw1CbPAYaV%2B7U2DGGJZcgoCvyoHmUAa0NpbV2vQAA1JGeMn8UDcA-smH%2BN0SD-xzBsgsz1ixfzAZWL6NZfr1g0KRTQexlbcjoWozWGw6FoMGHnNpdJtyJCbi8M2QtXFgtHj%2BJ4qDs7xPZi8RFrDoVtlVMM9GicOavjpC4BySt4IJ1KkQiZ-MiGBkCWfOQBy4wJkeZckA6ZWV3RuUA%2B5JY3rlnAVWb6tY-oAz2ISkKSD17Y3QTjRG4tspaLjiPWJzcQXpMsKkHmqVSqYOyhCrwJcRmWzynM5imV4ljM5toMGAQ4EULJd4lIXNBn8RdVYnoVJnXWtVZUQ4NrnAEh1VBCmVjeH6DGUPXBE5IoBG2FhURViwR9kLlpP2zMbD7jDaMbxdRM2YyNHm-VoasIwnjdiHGPz7RWMEUVHG0soUNysbiOtrrCrQWMHEtt0QtyOr9ouSOYISYhI7c0UeUNeKArEfHbucdfaaSnfw-IU5c22ujVW2NHsE2rAjSG3Vepw73k8f8ZtTr010Q7sa%2BSF5z3wntf8Xd%2BaASdHSNItO3Jsl5WqZYVmrr9w2ztK%2BwqwV92muNpMKw5iCmm28ZoTQhRNDpF8kIzx247bkr-Y%2B5hzEBI3ocPapmwi8pyv3GXUFTbEnzu9kGqwGcDQEZkDR6edGM0wT0u0btNiY79pVfaUeA7R0BE0FwvQejLjjjjpHFj%2BaUUGFtfMH9fwDyrH5hcJOszYr-JXm3J4wRQYOBcuWmO47LjepPnKxTynxL2xXp7HhWCtOiIMLp9VBhHgIWMyjaZS97WSdlT8eScmXVUcU5USzpRhY2ZnhrYWPEwijB7QxiwVgAgQecPYRj6L-Wd0JV7A8%2BsQtTsXP8%2BmMWwTxd0lYJLKXggSHS94g%2Buk%2BOhP1AizopJpaSJ8F0iQ5iEGVA4YUqTMNqHAXFe24TMlnC9aNQNv0NhhvR1G0ewEZgJPqSsdUCmsmvUKYPKFrw4W1MWqY7RbSdnFtnHm9N%2BJs3dILbnmk82ztmOoq8BFkwtgfBdQCJ9uKJQk4EP5ro-mP3-K-dsPzZRhgBaBE1Vt4xRhS32jNrrRT-ZPUwt0X0EZxi4sutHoxokr7fsrpKCZAh0Pd5efodM59WDKlhE1QMbVssfNiqPYgyJblrTxAbVQ-cGOwbyek3M4DKnrMDExOS7b-dohnFF-lvbhXztz0u9%2Bq2hnOYmi9o5V4XSnEfrHBFHWwuJEaj5n90ztrQlqyuD0%2BqHOInEWQRhQJw6bPis5879emxRSTeCzubGG2j5oN9PSkAsZ8CkEEPwfAYA0A0FueyzM1yHr5iekWXlZYBACpeVAkVDZSjrn3dqjFzYdLJ309CEdYxKkFWsZ2Ww5OShdcChXpHzjq8AVr%2BqnS7Vq8B6lFZyYbuzj2Er65rvCW6-j4%2B2Q2S9xhMLjtiZpOK%2BzgXD8EnZRlLq8T87zpbv7he-82h-PjmFxm%2Bk9X-1TpvV7%2BLyuDvtv4%2BO9Jz9NPk-JRlHn7bZfsn9%2BJOds4OOoa%2BdIOilu2%2BJQu%2B7eHM7%2BNex%2BVefeP2v%2Bki-%2BTegBlk4BP2oBt%2BI%2Bui8wUBo%2Be%2Bb%2BU%2BukM%2BJQXUqBQ%2BwmGBlwQB4Bzej%2BpOAsN%2Bq20BL%2BA%2Bki8Bp2XyBoFec%2Bfmf%2BVwV%2BK%2BW%2BeBJwH2hBT%2BHB5er%2BcBXBWkfBnCp%2Bw%2BMiwhS%2BFwYhY8LB0ONIRBMB8hbaPBWsyhnskOah0mNB0O0O%2BCEhkB9hU0U0zBz%2BchXB7QJh-6dkAyAhlhg%2B8ES%2BH2rId%2BC44hLBXUFoBhnB%2B%2BnhmG8qK2qhnY-h2UtBth9%2BLBTIYBI%2BOBOhrhNwsBxhihcRMsCR3%2Bfh1iGhNhgBJw6%2B6RYRwBPg0h7BxBBR3BA%2BuO%2B6OCuKemtaxePOQGNIZwK%2Bc2XOwUdiE%2BDak63h9hgQGoQ0PQNghOiB%2BIscToqaJgVgewU4nCds3qKxdkmq8IcctWDGFoQxRKPyW8N29hPRyhUKuU2G9hJxMyrSNCSEZSnGRcaKrsARuxGxHqzQ9GKxeMeu9hpmg6I2BckwwJjqja5xloGxl4qqo4129GVgo4R4LqpOJoIJ2uHet222LRRhbR9elaka9edSWxlh3qmxWE2S4GzOmswu2J4aFiVJQGPOTieRIowSSwSaKEgG7iCBy2bmxe6iOS%2BcHOOc%2B6LUmEqGIhJBChh%2Bn%2BSBFhzRu%2BxWroKsSRaE8pS%2BxJHhRRvwZhmcjC3JpI2a-mOIUInYZkJQ-Mga9MxBMunR-B7Q-RrJQEL6P%2B56CW2kkpMR7RZJOC6pjsiBXJrSh%2BYa-J9oOpfpaw%2Bp7hqpwaJK5ss%2BMhbujS9Q-unp8kAJ9Gwm9EDkSJxe8hmpMZCZpaBuqZRQSRfs8pk%2B7BZeNwReY4S6PiIoSKHirRhpyp5BX%2BAS1BARoh-i9RIRYR5pDQPZyZR%2BIp1eGBdZC%2B-%2By%2Bo5OhtRAsLhshSU05jZH%2B-ZyZ-ei5F%2BCpK5QsY5QsH2uBoZzYY%2BSZu5wpFBThQ5KRI5Z5a5jBABm5xBt5gZfZPeB5VBQhaBJ5Whq5zBwBdhX5GpiphRFsShIZ6ZR5lR6R2h4F4BAOuRW5dUO5B%2BUxnyCFABSFwFmh9hbBwBCUURN5MFJJeFmSBFh5z5i%2Br5kFWRP2X2mFzpkyjsMZ88biXZUk0ZFi5qOJCm8kAydZHW0Quiu%2BWZN5UmLCVF5ZQlfhup7MiZv5eF8OPhapk5slf4uiYIQ0a6WsaaNSqiglsu5RS5CpC5Pg4%2BtRoR75I%2BDpHFMlXFjSZ8Sy58WeVA8eFAeAsYSYSe10Ke2YaeoAGeICfKOezykCwq7yoyoxHCAibCHWlGZqFa3Y4sCJ6MNkE8b6Tmb2qk06oxWklZhc6mBaH2NKoSioVwPm5mDaSJzZ7QpKllnCoEYMeVDkk8SkRVVeJqWJHU9ibJeGsiPJ-iJwAcxWA8k6zMlJY1QE9uDCClbEneg1SRQpauwsZ6Mc246VKsh%2BAwlVgwSSOS3p56GwkuSVvyyGQG8IAyVi2xtk7c4i4cEaDSDc2JkiRxQFouYWqm9sk%2Bg1uWKcPq5sGoXEgNq8aq-VoK%2B1BV5V24J1WGZJaG8lS2QG1UVFEWUmVgTwd6Da4p66raL1nq8y8Rz1QK7c3oTJHZQG11xEyVqaX6llP47ZNCAuEs-wLorNrpZ6XNncyaQEgiMKJZA8Q0b1PQH1-BdsQGiu521iZ1Zu56Xh7a8NjNg8CoGo2FR20Jjp7aAe-1B2gNWmtGoN5cPxtEOuUNQNtcsN2uxVe1mtZVto1aylxa7Vht7cPQaN4s0u7cU4Z6VxKtu19ZLtC6X1OtHiGtpVU6vcocCNp2CZcK%2Bi7ls0mZeEZhft3Otit6FV4N81o1MuAIXUpI4enAiAvlWYAVQVFyoVACtykVDyoC-KsVQqbyMCHyrVN1xeQKoogtL10pqatGP4tNLp4irJOV-uF6%2BVp2uujtA17c84AwQ0ik3qmdPdTNt1GK7qxZZassjJ2suOpddEs07tYp2VvSlttFLqmdAG3yyludq8AWBdwK1NeEJ9J6gI%2BSrpJd7QKIyQQpncnaDxJ6Dcvcokltw9Dk5tcK-ovu4%2BeRnlQAA)

I'm not sure how to reproduce my problem, since the embed has a CORS issue in the REPL.

The problem is pretty simple: When I retreive an embed script like that from our backend as part of the body for an article. It works perfectly when I navigate straight to the page by typing in the URL in the browser. However, navigating to it from another page on the same site gives the result as shown in the REPL (but maybe due to a different reason).

If I knew how to describe it better, I would! Thanks for bearing with me here.

**Comment by paoloricciuti** [comment]
> > I'm not sure how to reproduce my problem, since the embed has a CORS issue in the REPL.
> 
> Create a clonable repo! Since SvelteLab doesn't currently offer download (AFAICT) I recommend either publishing something to GitHub, or using StackBlitz as suggested in the issue template.
> 
> > However, navigating to it from another page on the same site gives the result as shown in the REPL
> 
> That's because `<script>` executes synchronously when loading a page, but if you add it programmatically then it will execute whenever it happens to load, so it won't be ready by the time your component initializes. This isn't a Svelte/SvelteKit thing, it's just how browsers work.
> 
> If you want to wait until a script has loaded then you will need to add an onload handler e.g. in an `onMount`:
> 
> ```js
> onMount(() => {
>   const script = document.createElement('script');
>   script.onload = () => {
>     // ...
>   };
>   script.src = src;
> });
> ```

Just hopping in to say that sveltelab does in fact provide downloadable code. You can search for download in the command palette 😉
